import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-87-education-learning-skills-knowledge-cultural-capability-registry.json");
const phase86 = await readJson(appRoot, "src", "data", "phase-86-health-public-health-disability-population-wellbeing-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const school = registry.early_childhood_school_access_inclusion_learning_dossiers;
const postsecondary = registry.postsecondary_vocational_apprenticeship_affordability_ledgers;
const capability = registry.learning_capability_credential_skills_transition_registers;
const knowledge = registry.public_knowledge_culture_research_community_learning_ledgers;
const all = [...school, ...postsecondary, ...capability, ...knowledge];
check(registry.schema_version === "1.0" && registry.phase === "87", "The Phase 87 registry identity is invalid.");
check([school, postsecondary, capability, knowledge].every((records) => records.length === 8), "Phase 87 must contain eight records in each family.");
check(registry.school_access_gates.length === 20 && registry.postsecondary_pathway_gates.length === 20 && registry.learning_capability_gates.length === 22 && registry.public_knowledge_culture_gates.length === 22, "The Phase 87 gate counts must be 20/20/22/22.");
check(registry.education_access_settings.length === 14 && registry.education_inclusion_support_dimensions.length === 12 && registry.learning_condition_safeguards.length === 12 && registry.postsecondary_learning_pathways.length === 14 && registry.postsecondary_affordability_support_dimensions.length === 12 && registry.education_workforce_institution_continuity_safeguards.length === 12 && registry.learning_capability_domains.length === 14 && registry.assessment_credential_safeguards.length === 12 && registry.skills_work_civic_transition_dimensions.length === 12 && registry.public_knowledge_institutions.length === 12 && registry.research_public_knowledge_safeguards.length === 12 && registry.cultural_capability_dimensions.length === 12 && registry.long_horizon_human_development_tests.length === 12, "The Phase 87 controlled taxonomies are incomplete.");

const upstream = new Map(phase86.disability_equity_preparedness_population_wellbeing_ledgers.map((record) => [record.cohort_id, record]));
const taxonomyKeys = new Set(["education_access_setting_records", "education_inclusion_support_dimension_records", "learning_condition_safeguard_records", "postsecondary_learning_pathway_records", "postsecondary_affordability_support_dimension_records", "education_workforce_institution_continuity_safeguard_records", "learning_capability_domain_records", "assessment_credential_safeguard_records", "skills_work_civic_transition_dimension_records", "public_knowledge_institution_records", "research_public_knowledge_safeguard_records", "cultural_capability_dimension_records", "long_horizon_human_development_test_records"]);
for (let index = 0; index < 8; index += 1) {
  const s = school[index], p = postsecondary[index], c = capability[index], k = knowledge[index], u = upstream.get(s.cohort_id);
  check(Boolean(u) && s.disability_equity_preparedness_population_wellbeing_ledger_id === u.disability_equity_preparedness_population_wellbeing_ledger_id, `${s.early_childhood_school_access_inclusion_learning_dossier_id} has the wrong Phase 86 predecessor.`);
  check(s.school_checks.length === 20 && s.school_checks.every((item) => item.decision_state === "Inactive") && s.school_state.startsWith("Inactive") && s.school_decision === "Not Open", `${s.slug} is not inactive.`);
  check(s.education_access_setting_records.length === 14 && s.education_access_setting_records.every((item) => item.setting_state === "Unassessed") && s.education_inclusion_support_dimension_records.length === 12 && s.education_inclusion_support_dimension_records.every((item) => item.dimension_state === "Not Measured") && s.learning_condition_safeguard_records.length === 12 && s.learning_condition_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${s.slug} has an assigned school taxonomy.`);
  check(p.early_childhood_school_access_inclusion_learning_dossier_id === s.early_childhood_school_access_inclusion_learning_dossier_id && p.postsecondary_checks.length === 20 && p.postsecondary_checks.every((item) => item.decision_state === "Inactive") && p.postsecondary_state.startsWith("Inactive") && p.postsecondary_decision === "Not Open", `${p.slug} is not inactive.`);
  check(p.postsecondary_learning_pathway_records.length === 14 && p.postsecondary_learning_pathway_records.every((item) => item.pathway_state === "Unassessed") && p.postsecondary_affordability_support_dimension_records.length === 12 && p.postsecondary_affordability_support_dimension_records.every((item) => item.dimension_state === "Not Measured") && p.education_workforce_institution_continuity_safeguard_records.length === 12 && p.education_workforce_institution_continuity_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${p.slug} has an assigned postsecondary taxonomy.`);
  check(c.postsecondary_vocational_apprenticeship_affordability_ledger_id === p.postsecondary_vocational_apprenticeship_affordability_ledger_id && c.capability_checks.length === 22 && c.capability_checks.every((item) => item.decision_state === "Inactive") && c.capability_state.startsWith("Inactive") && c.capability_decision === "Not Open", `${c.slug} is not inactive.`);
  check(c.learning_capability_domain_records.length === 14 && c.learning_capability_domain_records.every((item) => item.domain_state === "Unassessed") && c.assessment_credential_safeguard_records.length === 12 && c.assessment_credential_safeguard_records.every((item) => item.safeguard_state === "Unverified") && c.skills_work_civic_transition_dimension_records.length === 12 && c.skills_work_civic_transition_dimension_records.every((item) => item.dimension_state === "Not Measured"), `${c.slug} has an assigned capability taxonomy.`);
  check(k.learning_capability_credential_skills_transition_register_id === c.learning_capability_credential_skills_transition_register_id && k.knowledge_checks.length === 22 && k.knowledge_checks.every((item) => item.decision_state === "Inactive") && k.knowledge_state.startsWith("Inactive") && k.knowledge_decision === "Not Open", `${k.slug} is not inactive.`);
  check(k.public_knowledge_institution_records.length === 12 && k.public_knowledge_institution_records.every((item) => item.institution_state === "Unassessed") && k.research_public_knowledge_safeguard_records.length === 12 && k.research_public_knowledge_safeguard_records.every((item) => item.safeguard_state === "Unverified") && k.cultural_capability_dimension_records.length === 12 && k.cultural_capability_dimension_records.every((item) => item.dimension_state === "Not Measured") && k.long_horizon_human_development_test_records.length === 12 && k.long_horizon_human_development_test_records.every((item) => item.test_state === "Not Tested"), `${k.slug} has an assigned knowledge taxonomy.`);
}
for (const record of all) {
  check(record.propagation_status === "not_started" && record.first_reviewer_id === null && record.second_reviewer_id === null && record.phase64_cell_change === "none", `${record.slug} contains a premature review or advance.`);
  for (const [key, value] of Object.entries(record)) {
    if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
    if (key.endsWith("_receipt_id")) check(value === null, `${record.slug} contains ${key}.`);
    if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} contains non-taxonomy ${key}.`);
  }
}
const countMetrics = new Set(["early_childhood_school_access_inclusion_learning_dossiers", "postsecondary_vocational_apprenticeship_affordability_ledgers", "learning_capability_credential_skills_transition_registers", "public_knowledge_culture_research_community_learning_ledgers", "school_access_gates", "postsecondary_pathway_gates", "learning_capability_gates", "public_knowledge_culture_gates", "education_access_settings", "education_inclusion_support_dimensions", "learning_condition_safeguards", "postsecondary_learning_pathways", "postsecondary_affordability_support_dimensions", "education_workforce_institution_continuity_safeguards", "learning_capability_domains", "assessment_credential_safeguards", "skills_work_civic_transition_dimensions", "public_knowledge_institutions", "research_public_knowledge_safeguards", "cultural_capability_dimensions", "long_horizon_human_development_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!countMetrics.has(key)) check(value === 0, `Phase 87 metric ${key} must remain zero.`);

const guides = ["education-human-development-doctrine-001", "early-childhood-family-development-001", "school-attendance-access-learning-inclusion-001", "disability-language-accessible-inclusive-education-001", "indigenous-education-jurisdiction-knowledge-language-001", "teachers-education-workers-institutional-capacity-001", "postsecondary-affordability-student-support-001", "vocational-apprenticeship-skills-recognition-001", "learning-assessment-credential-capability-001", "libraries-digital-access-media-information-literacy-001", "research-public-knowledge-translation-001", "arts-culture-community-learning-recovery-001"];
const maps = ["enrollment-is-not-learning", "credential-is-not-demonstrated-capability", "training-seat-is-not-access-to-decent-work", "published-research-is-not-usable-public-knowledge", "digital-access-is-not-information-literacy", "institution-reopening-is-not-community-learning-recovery"];
for (const slug of guides) check(await exists(appRoot, "src", "content", "briefings", "briefing-" + slug + ".mdx"), `Phase 87 guide ${slug} is missing.`);
for (const slug of maps) check(await exists(appRoot, "src", "content", "dependency-maps", slug + ".json"), `Phase 87 map ${slug} is missing.`);
const guideIds = guides.map((slug) => "briefing-" + slug), mapIds = maps.map((slug) => "dependency-map-" + slug);
for (const pathwayId of new Set(school.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 87 content.`); }
for (const id of new Set(school.map((record) => record.canonical_briefing_id))) check((await readText(appRoot, "src", "content", "briefings", id + ".mdx")).includes("## Phase 87 education and cultural-capability boundary"), `${id} omits the Phase 87 named-file boundary.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 87 education, learning, skills, knowledge, and cultural-capability boundary"), `${file} omits Phase 87.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-universal-service-doctrine-001.mdx", "briefing-household-capability-doctrine-001.mdx", "briefing-community-institutions-doctrine-001.mdx", "briefing-essential-service-bundles-households-001.mdx", "briefing-disability-universal-design-home-community-001.mdx", "briefing-accessibility-user-rights-remedy-001.mdx", "briefing-libraries-schools-clinics-civic-infrastructure-001.mdx", "briefing-trusted-intermediaries-public-knowledge-001.mdx", "briefing-local-media-information-integrity-001.mdx", "briefing-cultural-faith-indigenous-place-governance-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 87 education and cultural-capability control"), `${file} omits the Phase 87 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "education-knowledge-culture", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "education-knowledge-culture", "[id].astro") && await exists(appRoot, "src", "pages", "data", "education-learning-skills-knowledge-cultural-capability.json.ts"), "Phase 87 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Education, Learning, Skills, Knowledge And Cultural Capability") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 87.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("educationKnowledgeCultureRegistry") && sitemap.includes("/evidence/education-knowledge-culture/"), "The sitemap omits Phase 87.");
const phase86Detail = await readText(appRoot, "src", "pages", "evidence", "health-population-wellbeing", "[id].astro");
check(phase86Detail.includes("Phase 87 Destination") && phase86Detail.includes("/evidence/education-knowledge-culture/"), "Phase 86 detail routes omit the Phase 87 handoff.");
check(manifest.expected_build.static_pages >= 4999 && manifest.expected_build.public_json_exports >= 34 && manifest.expected_build.phase_87_early_childhood_school_access_inclusion_learning_dossiers === 8 && manifest.expected_build.phase_87_postsecondary_vocational_apprenticeship_affordability_ledgers === 8 && manifest.expected_build.phase_87_learning_capability_credential_skills_transition_registers === 8 && manifest.expected_build.phase_87_public_knowledge_culture_research_community_learning_ledgers === 8 && manifest.expected_build.phase_87_synthetic_cases === 2560, "The release manifest omits Phase 87 counts.");
check(manifest.early_childhood_school_access_inclusion_learning_routes?.length === 8 && manifest.postsecondary_vocational_apprenticeship_affordability_routes?.length === 8 && manifest.learning_capability_credential_skills_transition_routes?.length === 8 && manifest.public_knowledge_culture_research_community_learning_routes?.length === 8, "The release manifest omits Phase 87 routes.");
check(await exists(workspaceRoot, "docs", "work-packages", "phase-87-education-learning-skills-knowledge-cultural-capability.md"), "The Phase 87 work package is missing.");

if (failures.length) {
  console.error(`Phase 87 assertions failed with ${failures.length} issue(s):`);
  failures.forEach((failure) => console.error(`- ${failure}`));
  process.exit(1);
}
console.log("Phase 87 assertions passed: 8 inactive school dossiers, 8 inactive postsecondary ledgers, 8 inactive capability registers, 8 inactive public-knowledge ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 enrollment, credential, learning, capability, transition, culture, recovery, score, ranking, or Phase 64 decisions.");
