import { readFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readText = async (...parts) => readFile(join(...parts), "utf8");
const readJson = async (...parts) => JSON.parse(await readText(...parts));
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };
const isEmpty = (value) => Array.isArray(value) ? value.length === 0 : value && typeof value === "object" ? Object.keys(value).length === 0 : value === null || value === "";

const registry = await readJson(appRoot, "src", "data", "phase-81-universal-service-essential-systems-public-option-delivery-registry.json");
const phase80 = await readJson(appRoot, "src", "data", "phase-80-public-investment-portfolios-transition-pathways-place-based-capacity-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const floors = registry.service_floor_universal_access_dossiers;
const affordability = registry.affordability_cross_subsidy_coverage_ledgers;
const providers = registry.provider_plurality_interoperability_continuity_registers;
const restoration = registry.rights_quality_step_in_restoration_ledgers;

check(registry.phase === "81" && registry.schema_version === "1.0", "Phase 81 registry identity is invalid.");
check(floors.length === 8 && affordability.length === 8 && providers.length === 8 && restoration.length === 8, "Phase 81 record-family counts are invalid.");
check(registry.service_floor_gates.length === 20 && registry.affordability_coverage_gates.length === 20 && registry.provider_continuity_gates.length === 22 && registry.rights_restoration_gates.length === 22, "Phase 81 gate counts are invalid.");
for (const [name, expected] of [["essential_service_classes", 14], ["service_floor_dimensions", 14], ["eligibility_access_duties", 12], ["affordability_protections", 12], ["cross_subsidy_mechanisms", 12], ["coverage_access_dimensions", 12], ["provider_operating_models", 12], ["interoperability_requirements", 14], ["continuity_mutual_aid_capabilities", 12], ["user_rights_remedies", 14], ["service_quality_reliability_measures", 14], ["provider_failure_step_in_triggers", 12], ["emergency_rationing_restoration_duties", 12]]) check(registry[name].length === expected, `Phase 81 ${name} count is invalid.`);

const all = [...floors, ...affordability, ...providers, ...restoration];
const ids = all.map((record) => Object.values(record).find((value) => typeof value === "string" && /^81-(SFD|ACL|PIC|RQR)-/.test(value)));
check(new Set(ids).size === 32 && new Set(all.map((record) => record.slug)).size === 32, "Phase 81 IDs or slugs are not unique.");
check(new Set(floors.map((record) => record.portfolio_stress_rebalancing_realization_ledger_id)).size === 8, "Phase 80 realization records do not map one-to-one to Phase 81 floors.");
check(floors.every((record) => phase80.portfolio_stress_rebalancing_realization_ledgers.some((item) => item.portfolio_stress_rebalancing_realization_ledger_id === record.portfolio_stress_rebalancing_realization_ledger_id && item.cohort_id === record.cohort_id)), "A Phase 81 floor lacks its exact Phase 80 predecessor.");

floors.forEach((record) => {
  check(record.service_floor_state === "Inactive - No Verified Phase 80 Portfolio Realization Record" && record.adoption_decision === "Not Open", `${record.service_floor_universal_access_dossier_id} is not inactive.`);
  check(record.service_floor_checks.length === 20 && record.service_floor_checks.every((item) => item.decision_state === "Inactive"), `${record.service_floor_universal_access_dossier_id} has an active gate.`);
  check(record.essential_service_class_records.length === 14 && record.essential_service_class_records.every((item) => item.classification_state === "Unassigned" && isEmpty(item.authority_ids) && isEmpty(item.evidence_ids) && item.decision_id === null), `${record.service_floor_universal_access_dossier_id} contains a service classification.`);
  check(record.service_floor_dimension_records.length === 14 && record.service_floor_dimension_records.every((item) => item.floor_state === "Not Defined" && isEmpty(item.standard_ids) && isEmpty(item.threshold_ids) && isEmpty(item.evidence_ids)), `${record.service_floor_universal_access_dossier_id} contains a service floor.`);
  check(record.eligibility_access_duty_records.length === 12 && record.eligibility_access_duty_records.every((item) => item.duty_state === "Unassigned" && isEmpty(item.population_ids) && isEmpty(item.owner_ids) && isEmpty(item.remedy_ids)), `${record.service_floor_universal_access_dossier_id} contains an access duty.`);
  for (const field of ["verified_phase80_realization_record_ids", "authority_records", "essential_service_records", "eligible_public_records", "service_floor_records", "baseline_records", "unmet_need_records", "access_records", "eligibility_records", "nondiscrimination_records", "capacity_records", "place_coverage_records", "provider_duty_records", "funding_records", "standard_records", "rights_records", "continuity_records", "option_records"]) check(isEmpty(record[field]), `${record.service_floor_universal_access_dossier_id} contains premature ${field}.`);
  check(record.first_reviewer_id === null && record.second_reviewer_id === null && record.service_floor_receipt_id === null && record.infrastructure_as_access_allowed === false && record.provider_presence_as_universal_service_allowed === false && record.average_service_as_floor_allowed === false && record.automatic_service_classification_allowed === false && record.automatic_floor_adoption_allowed === false && record.automatic_eligibility_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.service_floor_universal_access_dossier_id} violates a boundary.`);
});

affordability.forEach((record, index) => {
  check(record.affordability_state === "Inactive - No Adopted Essential-Service Floor" && record.affordability_decision === "Not Open" && record.service_floor_universal_access_dossier_id === floors[index].service_floor_universal_access_dossier_id, `${record.affordability_cross_subsidy_coverage_ledger_id} is not inactive or linked.`);
  check(record.affordability_coverage_checks.length === 20 && record.affordability_coverage_checks.every((item) => item.decision_state === "Inactive"), `${record.affordability_cross_subsidy_coverage_ledger_id} has an active gate.`);
  check(record.affordability_protection_records.length === 12 && record.affordability_protection_records.every((item) => item.protection_state === "Unassessed" && isEmpty(item.authority_ids) && isEmpty(item.funding_ids) && isEmpty(item.beneficiary_ids)), `${record.affordability_cross_subsidy_coverage_ledger_id} contains a protection finding.`);
  check(record.cross_subsidy_mechanism_records.length === 12 && record.cross_subsidy_mechanism_records.every((item) => item.mechanism_state === "Unassessed" && isEmpty(item.contributor_ids) && isEmpty(item.beneficiary_ids) && item.allocation_rule_id === null), `${record.affordability_cross_subsidy_coverage_ledger_id} contains a subsidy decision.`);
  check(record.coverage_access_dimension_records.length === 12 && record.coverage_access_dimension_records.every((item) => item.measurement_state === "Not Measured" && isEmpty(item.geography_ids) && isEmpty(item.population_ids) && isEmpty(item.observation_ids)), `${record.affordability_cross_subsidy_coverage_ledger_id} contains a coverage finding.`);
  for (const field of ["cost_records", "ability_to_pay_records", "burden_records", "protection_records", "funding_records", "subsidy_records", "cross_subsidy_records", "network_coverage_records", "connection_records", "take_up_records", "capacity_records", "disaggregation_records", "quality_parity_records", "public_option_records", "scenario_records", "trigger_records"]) check(isEmpty(record[field]), `${record.affordability_cross_subsidy_coverage_ledger_id} contains premature ${field}.`);
  check(record.first_reviewer_id === null && record.second_reviewer_id === null && record.affordability_receipt_id === null && record.average_price_as_affordability_allowed === false && record.network_presence_as_access_allowed === false && record.subsidy_as_service_outcome_allowed === false && record.automatic_tariff_allowed === false && record.automatic_subsidy_allowed === false && record.automatic_expansion_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.affordability_cross_subsidy_coverage_ledger_id} violates a boundary.`);
});

providers.forEach((record, index) => {
  check(record.provider_state === "Inactive - No Verified Affordability And Coverage Record" && record.provider_decision === "Not Open" && record.affordability_cross_subsidy_coverage_ledger_id === affordability[index].affordability_cross_subsidy_coverage_ledger_id, `${record.provider_plurality_interoperability_continuity_register_id} is not inactive or linked.`);
  check(record.provider_continuity_checks.length === 22 && record.provider_continuity_checks.every((item) => item.decision_state === "Inactive"), `${record.provider_plurality_interoperability_continuity_register_id} has an active gate.`);
  check(record.provider_operating_model_records.length === 12 && record.provider_operating_model_records.every((item) => item.model_state === "Unassessed" && isEmpty(item.provider_ids) && isEmpty(item.authority_ids) && isEmpty(item.duty_ids)), `${record.provider_plurality_interoperability_continuity_register_id} contains a provider finding.`);
  check(record.interoperability_requirement_records.length === 14 && record.interoperability_requirement_records.every((item) => item.requirement_state === "Unverified" && isEmpty(item.standard_ids) && isEmpty(item.conformance_ids) && isEmpty(item.exception_ids)), `${record.provider_plurality_interoperability_continuity_register_id} contains an interoperability finding.`);
  check(record.continuity_mutual_aid_capability_records.length === 12 && record.continuity_mutual_aid_capability_records.every((item) => item.capability_state === "Untested" && isEmpty(item.owner_ids) && isEmpty(item.exercise_ids) && isEmpty(item.receipt_ids)), `${record.provider_plurality_interoperability_continuity_register_id} contains a continuity finding.`);
  for (const field of ["provider_records", "plurality_records", "concentration_records", "open_standard_records", "interface_records", "conformance_records", "data_governance_records", "portability_records", "procurement_and_license_records", "performance_records", "maintenance_records", "reserve_records", "mutual_aid_records", "continuity_plan_records", "security_records", "dependency_records", "common_mode_records", "exercise_records", "step_in_readiness_records", "orderly_exit_records"]) check(isEmpty(record[field]), `${record.provider_plurality_interoperability_continuity_register_id} contains premature ${field}.`);
  check(record.first_reviewer_id === null && record.second_reviewer_id === null && record.provider_receipt_id === null && record.provider_count_as_plurality_allowed === false && record.technical_interface_as_interoperability_allowed === false && record.backup_plan_as_continuity_allowed === false && record.automatic_provider_selection_allowed === false && record.automatic_standard_adoption_allowed === false && record.automatic_mutual_aid_activation_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.provider_plurality_interoperability_continuity_register_id} violates a boundary.`);
});

restoration.forEach((record, index) => {
  check(record.restoration_state === "Inactive - No Verified Provider Continuity Baseline" && record.intervention_decision === "Not Open" && record.provider_plurality_interoperability_continuity_register_id === providers[index].provider_plurality_interoperability_continuity_register_id, `${record.rights_quality_step_in_restoration_ledger_id} is not inactive or linked.`);
  check(record.rights_restoration_checks.length === 22 && record.rights_restoration_checks.every((item) => item.decision_state === "Inactive"), `${record.rights_quality_step_in_restoration_ledger_id} has an active gate.`);
  check(record.user_right_remedy_records.length === 14 && record.user_right_remedy_records.every((item) => item.right_state === "Unadopted" && isEmpty(item.authority_ids) && isEmpty(item.complaint_ids) && isEmpty(item.remedy_ids)), `${record.rights_quality_step_in_restoration_ledger_id} contains a rights finding.`);
  check(record.service_quality_reliability_measure_records.length === 14 && record.service_quality_reliability_measure_records.every((item) => item.measure_state === "Not Measured" && isEmpty(item.standard_ids) && isEmpty(item.observation_ids) && item.finding_id === null), `${record.rights_quality_step_in_restoration_ledger_id} contains a quality finding.`);
  check(record.provider_failure_step_in_trigger_records.length === 12 && record.provider_failure_step_in_trigger_records.every((item) => item.trigger_state === "Dormant" && isEmpty(item.event_ids) && item.review_id === null && item.decision_id === null), `${record.rights_quality_step_in_restoration_ledger_id} contains a failure trigger.`);
  check(record.emergency_rationing_restoration_duty_records.length === 12 && record.emergency_rationing_restoration_duty_records.every((item) => item.duty_state === "Unassigned" && isEmpty(item.priority_ids) && isEmpty(item.owner_ids) && isEmpty(item.receipt_ids)), `${record.rights_quality_step_in_restoration_ledger_id} contains a restoration priority.`);
  for (const field of ["rights_charter_records", "notice_records", "complaint_records", "appeal_records", "remedy_records", "quality_standard_records", "reliability_observation_records", "maintenance_performance_records", "failure_event_records", "early_warning_records", "intervention_option_records", "step_in_authority_records", "continuity_transition_records", "emergency_declaration_records", "rationing_records", "restoration_records", "normalization_records", "long_horizon_accountability_records", "corrective_action_records"]) check(isEmpty(record[field]), `${record.rights_quality_step_in_restoration_ledger_id} contains premature ${field}.`);
  check(record.first_reviewer_id === null && record.second_reviewer_id === null && record.restoration_receipt_id === null && record.average_uptime_as_universal_quality_allowed === false && record.emergency_as_permanent_reduction_allowed === false && record.provider_failure_as_automatic_step_in_allowed === false && record.automatic_rights_finding_allowed === false && record.automatic_intervention_allowed === false && record.automatic_rationing_allowed === false && record.automatic_restoration_priority_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.rights_quality_step_in_restoration_ledger_id} violates a boundary.`);
});

const nonZeroMetrics = new Set(["service_floor_universal_access_dossiers", "affordability_cross_subsidy_coverage_ledgers", "provider_plurality_interoperability_continuity_registers", "rights_quality_step_in_restoration_ledgers", "service_floor_gates", "affordability_coverage_gates", "provider_continuity_gates", "rights_restoration_gates", "essential_service_classes", "service_floor_dimensions", "eligibility_access_duties", "affordability_protections", "cross_subsidy_mechanisms", "coverage_access_dimensions", "provider_operating_models", "interoperability_requirements", "continuity_mutual_aid_capabilities", "user_rights_remedies", "service_quality_reliability_measures", "provider_failure_step_in_triggers", "emergency_rationing_restoration_duties"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!nonZeroMetrics.has(key)) check(value === 0, `Phase 81 metric ${key} must remain zero.`);

const guideIds = ["briefing-universal-service-doctrine-001", "briefing-essential-service-floors-001", "briefing-eligibility-access-nondiscrimination-001", "briefing-affordability-cross-subsidy-001", "briefing-coverage-capacity-access-001", "briefing-public-options-provider-plurality-001", "briefing-interoperability-open-standards-data-portability-001", "briefing-accessibility-user-rights-remedy-001", "briefing-continuity-mutual-aid-essential-systems-001", "briefing-service-quality-reliability-state-good-repair-001", "briefing-provider-failure-step-in-public-option-001", "briefing-emergency-rationing-restoration-long-horizon-accountability-001"];
for (const id of guideIds) { const body = await readText(appRoot, "src", "content", "briefings", id + ".mdx"); check(body.includes('record_status: "Published"') && body.length > 12000 && body.includes("## Public contract"), `${id} is missing, short, or not Published.`); }
const mapSlugs = ["infrastructure-coverage-is-not-service-access", "low-average-price-is-not-affordability", "provider-presence-is-not-universal-service", "technical-interface-is-not-interoperability-rights", "average-uptime-is-not-universal-quality", "emergency-rationing-is-not-permanent-service-reduction"];
const mapIds = [];
for (const slug of mapSlugs) { const map = await readJson(appRoot, "src", "content", "dependency-maps", slug + ".json"); mapIds.push(map.id); check(map.record_status === "Published" && map.nodes.length === 7 && map.links.length === 6 && map.interpretation_boundary.includes("does not establish"), `${slug} is invalid.`); }
const pathwayIds = [...new Set(floors.flatMap((record) => record.reader_pathway_ids))];
check(pathwayIds.length === 10, `Expected 10 pathway integrations, found ${pathwayIds.length}.`);
for (const pathwayId of pathwayIds) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 81 guides or maps.`); }
for (const record of floors) check((await readText(appRoot, "src", "content", "briefings", record.canonical_briefing_id + ".mdx")).includes("## Phase 81 universal-service and essential-systems boundary"), `${record.canonical_briefing_id} omits Phase 81.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 81 universal-service, affordability, continuity, and rights boundary"), `${file} omits Phase 81.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-fiscal-capacity-contribution-sharing-001.mdx", "briefing-public-wealth-balance-sheet-001.mdx", "briefing-public-investment-doctrine-001.mdx", "briefing-portfolio-construction-without-ranking-001.mdx", "briefing-place-based-value-just-transition-001.mdx", "briefing-public-value-realization-transition-accountability-001.mdx", "briefing-emergency-powers-civil-safeguards-001.mdx", "briefing-emergency-authority-normalization-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 81 universal-service, public-option, and restoration control"), `${file} omits the Phase 81 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "essential-services", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "essential-services", "[id].astro") && await exists(appRoot, "src", "pages", "data", "universal-service-essential-systems-public-options.json.ts"), "Phase 81 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Universal Service And Essential Systems") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 81.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("universalServiceRegistry") && sitemap.includes("/evidence/essential-services/"), "The sitemap omits Phase 81.");
const phase80Detail = await readText(appRoot, "src", "pages", "evidence", "investment-portfolios", "[id].astro");
check(phase80Detail.includes("Phase 81 Destination") && phase80Detail.includes("/evidence/essential-services/"), "Phase 80 detail routes omit the Phase 81 handoff.");
check(manifest.expected_build.static_pages >= 4693 && manifest.expected_build.public_json_exports >= 28 && manifest.expected_build.phase_81_service_floor_universal_access_dossiers === 8 && manifest.expected_build.phase_81_affordability_cross_subsidy_coverage_ledgers === 8 && manifest.expected_build.phase_81_provider_plurality_interoperability_continuity_registers === 8 && manifest.expected_build.phase_81_rights_quality_step_in_restoration_ledgers === 8 && manifest.expected_build.phase_81_synthetic_cases === 2560, "The release manifest omits Phase 81 counts.");
check(manifest.service_floor_universal_access_routes?.length === 8 && manifest.affordability_cross_subsidy_coverage_routes?.length === 8 && manifest.provider_plurality_interoperability_continuity_routes?.length === 8 && manifest.rights_quality_step_in_restoration_routes?.length === 8, "The release manifest omits Phase 81 routes.");

if (failures.length) { console.error(`Phase 81 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 81 assertions passed: 8 inactive service-floor dossiers, 8 inactive affordability-coverage ledgers, 8 inactive provider-continuity registers, 8 inactive rights-restoration ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 floors, tariffs, subsidies, providers, standards, interventions, restoration priorities, remedies, receipts, scores, rankings, or stage changes.");
