import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-88-work-labor-livelihoods-economic-democracy-registry.json");
const phase87 = await readJson(appRoot, "src", "data", "phase-87-education-learning-skills-knowledge-cultural-capability-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const accessRecords = registry.job_access_matching_hiring_nondiscrimination_dossiers;
const qualityRecords = registry.job_quality_wages_benefits_hours_safety_ledgers;
const voiceRecords = registry.worker_voice_organizing_collective_bargaining_economic_democracy_registers;
const livelihoodRecords = registry.livelihood_security_displacement_just_transition_long_horizon_ledgers;
const all = [...accessRecords, ...qualityRecords, ...voiceRecords, ...livelihoodRecords];
check(registry.schema_version === "1.0" && registry.phase === "88", "The Phase 88 registry identity is invalid.");
check([accessRecords, qualityRecords, voiceRecords, livelihoodRecords].every((records) => records.length === 8), "Phase 88 must contain eight records in each family.");
check(registry.job_access_gates.length === 20 && registry.job_quality_gates.length === 20 && registry.worker_voice_gates.length === 22 && registry.livelihood_security_gates.length === 22, "The Phase 88 gate counts must be 20/20/22/22.");
check(registry.labor_market_access_channels.length === 14 && registry.hiring_access_equity_dimensions.length === 12 && registry.job_matching_recruitment_safeguards.length === 12 && registry.employment_arrangement_classes.length === 14 && registry.job_quality_compensation_dimensions.length === 12 && registry.workplace_health_safety_continuity_safeguards.length === 12 && registry.worker_voice_representation_models.length === 14 && registry.organizing_collective_bargaining_safeguards.length === 12 && registry.economic_democracy_ownership_dimensions.length === 12 && registry.livelihood_security_support_systems.length === 12 && registry.displacement_transition_safeguards.length === 12 && registry.regional_labor_market_equity_dimensions.length === 12 && registry.long_horizon_economic_agency_tests.length === 12, "The Phase 88 controlled taxonomies are incomplete.");
check(["A job posting is not an available job", "employment is not decent work", "a wage rate is not household livelihood security", "training completion is not durable career mobility", "worker consultation is not bargaining power", "reemployment is not a just transition"].every((boundary) => registry.interpretation_boundary.toLowerCase().includes(boundary.toLowerCase())), "The Phase 88 non-substitution boundary is incomplete.");

const upstream = new Map(phase87.public_knowledge_culture_research_community_learning_ledgers.map((record) => [record.cohort_id, record]));
const taxonomyKeys = new Set(["labor_market_access_channel_records", "hiring_access_equity_dimension_records", "job_matching_recruitment_safeguard_records", "employment_arrangement_class_records", "job_quality_compensation_dimension_records", "workplace_health_safety_continuity_safeguard_records", "worker_voice_representation_model_records", "organizing_collective_bargaining_safeguard_records", "economic_democracy_ownership_dimension_records", "livelihood_security_support_system_records", "displacement_transition_safeguard_records", "regional_labor_market_equity_dimension_records", "long_horizon_economic_agency_test_records"]);
for (let index = 0; index < 8; index += 1) {
  const a = accessRecords[index], q = qualityRecords[index], v = voiceRecords[index], l = livelihoodRecords[index], u = upstream.get(a.cohort_id);
  check(Boolean(u) && a.public_knowledge_culture_research_community_learning_ledger_id === u.public_knowledge_culture_research_community_learning_ledger_id, `${a.job_access_matching_hiring_nondiscrimination_dossier_id} has the wrong Phase 87 predecessor.`);
  check(a.job_access_checks.length === 20 && a.job_access_checks.every((item) => item.decision_state === "Inactive") && a.job_access_state.startsWith("Inactive") && a.job_access_decision === "Not Open", `${a.slug} is not inactive.`);
  check(a.labor_market_access_channel_records.length === 14 && a.labor_market_access_channel_records.every((item) => item.channel_state === "Unassessed") && a.hiring_access_equity_dimension_records.length === 12 && a.hiring_access_equity_dimension_records.every((item) => item.dimension_state === "Not Measured") && a.job_matching_recruitment_safeguard_records.length === 12 && a.job_matching_recruitment_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${a.slug} has an assigned job-access taxonomy.`);
  check(q.job_access_matching_hiring_nondiscrimination_dossier_id === a.job_access_matching_hiring_nondiscrimination_dossier_id && q.job_quality_checks.length === 20 && q.job_quality_checks.every((item) => item.decision_state === "Inactive") && q.job_quality_state.startsWith("Inactive") && q.job_quality_decision === "Not Open", `${q.slug} is not inactive.`);
  check(q.employment_arrangement_class_records.length === 14 && q.employment_arrangement_class_records.every((item) => item.arrangement_state === "Unassessed") && q.job_quality_compensation_dimension_records.length === 12 && q.job_quality_compensation_dimension_records.every((item) => item.dimension_state === "Not Measured") && q.workplace_health_safety_continuity_safeguard_records.length === 12 && q.workplace_health_safety_continuity_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${q.slug} has an assigned job-quality taxonomy.`);
  check(v.job_quality_wages_benefits_hours_safety_ledger_id === q.job_quality_wages_benefits_hours_safety_ledger_id && v.worker_voice_checks.length === 22 && v.worker_voice_checks.every((item) => item.decision_state === "Inactive") && v.worker_voice_state.startsWith("Inactive") && v.worker_voice_decision === "Not Open", `${v.slug} is not inactive.`);
  check(v.worker_voice_representation_model_records.length === 14 && v.worker_voice_representation_model_records.every((item) => item.model_state === "Unassessed") && v.organizing_collective_bargaining_safeguard_records.length === 12 && v.organizing_collective_bargaining_safeguard_records.every((item) => item.safeguard_state === "Unverified") && v.economic_democracy_ownership_dimension_records.length === 12 && v.economic_democracy_ownership_dimension_records.every((item) => item.dimension_state === "Not Measured"), `${v.slug} has an assigned worker-voice taxonomy.`);
  check(l.worker_voice_organizing_collective_bargaining_economic_democracy_register_id === v.worker_voice_organizing_collective_bargaining_economic_democracy_register_id && l.livelihood_checks.length === 22 && l.livelihood_checks.every((item) => item.decision_state === "Inactive") && l.livelihood_state.startsWith("Inactive") && l.livelihood_decision === "Not Open", `${l.slug} is not inactive.`);
  check(l.livelihood_security_support_system_records.length === 12 && l.livelihood_security_support_system_records.every((item) => item.system_state === "Unassessed") && l.displacement_transition_safeguard_records.length === 12 && l.displacement_transition_safeguard_records.every((item) => item.safeguard_state === "Unverified") && l.regional_labor_market_equity_dimension_records.length === 12 && l.regional_labor_market_equity_dimension_records.every((item) => item.dimension_state === "Not Measured") && l.long_horizon_economic_agency_test_records.length === 12 && l.long_horizon_economic_agency_test_records.every((item) => item.test_state === "Not Tested"), `${l.slug} has an assigned livelihood taxonomy.`);
}
for (const record of all) {
  check(record.propagation_status === "not_started" && record.first_reviewer_id === null && record.second_reviewer_id === null && record.phase64_cell_change === "none", `${record.slug} contains a premature review or advance.`);
  for (const [key, value] of Object.entries(record)) {
    if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
    if (key.endsWith("_receipt_id")) check(value === null, `${record.slug} contains ${key}.`);
    if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} contains non-taxonomy ${key}.`);
  }
}
const countMetrics = new Set(["job_access_matching_hiring_nondiscrimination_dossiers", "job_quality_wages_benefits_hours_safety_ledgers", "worker_voice_organizing_collective_bargaining_economic_democracy_registers", "livelihood_security_displacement_just_transition_long_horizon_ledgers", "job_access_gates", "job_quality_gates", "worker_voice_gates", "livelihood_security_gates", "labor_market_access_channels", "hiring_access_equity_dimensions", "job_matching_recruitment_safeguards", "employment_arrangement_classes", "job_quality_compensation_dimensions", "workplace_health_safety_continuity_safeguards", "worker_voice_representation_models", "organizing_collective_bargaining_safeguards", "economic_democracy_ownership_dimensions", "livelihood_security_support_systems", "displacement_transition_safeguards", "regional_labor_market_equity_dimensions", "long_horizon_economic_agency_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!countMetrics.has(key)) check(value === 0, `Phase 88 metric ${key} must remain zero.`);

const guides = ["work-labor-livelihoods-economic-democracy-doctrine-001", "job-access-matching-hiring-001", "job-quality-decent-work-001", "wages-benefits-household-livelihood-security-001", "hours-scheduling-time-autonomy-001", "worker-health-safety-dignity-001", "worker-voice-organizing-collective-bargaining-001", "platform-gig-informal-contingent-work-001", "care-domestic-agricultural-migrant-work-001", "automation-climate-industrial-transition-001", "cooperatives-employee-ownership-public-employment-001", "labor-standards-enforcement-remedy-001"];
const maps = ["job-posting-is-not-available-job", "employment-is-not-decent-work", "wage-rate-is-not-household-livelihood-security", "training-completion-is-not-durable-career-mobility", "worker-consultation-is-not-bargaining-power", "reemployment-is-not-just-transition"];
for (const slug of guides) check(await exists(appRoot, "src", "content", "briefings", "briefing-" + slug + ".mdx"), `Phase 88 guide ${slug} is missing.`);
for (const slug of maps) check(await exists(appRoot, "src", "content", "dependency-maps", slug + ".json"), `Phase 88 map ${slug} is missing.`);
const guideIds = guides.map((slug) => "briefing-" + slug), mapIds = maps.map((slug) => "dependency-map-" + slug);
for (const pathwayId of new Set(accessRecords.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 88 content.`); }
for (const id of new Set(accessRecords.map((record) => record.canonical_briefing_id))) check((await readText(appRoot, "src", "content", "briefings", id + ".mdx")).includes("## Phase 88 work, labor, livelihoods, and economic-democracy boundary"), `${id} omits the Phase 88 named-file boundary.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 88 work, labor, livelihoods, and economic-democracy boundary"), `${file} omits Phase 88.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-household-capability-doctrine-001.mdx", "briefing-community-institutions-doctrine-001.mdx", "briefing-care-infrastructure-workforce-001.mdx", "briefing-teachers-education-workers-institutional-capacity-001.mdx", "briefing-vocational-apprenticeship-skills-recognition-001.mdx", "briefing-learning-assessment-credential-capability-001.mdx", "briefing-public-investment-doctrine-001.mdx", "briefing-workforce-supplier-readiness-001.mdx", "briefing-place-based-value-just-transition-001.mdx", "briefing-cooperatives-community-ownership-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 88 labor, livelihood, and economic-democracy control"), `${file} omits the Phase 88 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "work-labor-livelihoods", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "work-labor-livelihoods", "[id].astro") && await exists(appRoot, "src", "pages", "data", "work-labor-livelihoods-economic-democracy.json.ts"), "Phase 88 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Work, Labor, Livelihoods And Economic Democracy") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 88.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("workLaborLivelihoodsRegistry") && sitemap.includes("/evidence/work-labor-livelihoods/"), "The sitemap omits Phase 88.");
const phase87Detail = await readText(appRoot, "src", "pages", "evidence", "education-knowledge-culture", "[id].astro");
check(phase87Detail.includes("Phase 88 Destination") && phase87Detail.includes("/evidence/work-labor-livelihoods/"), "Phase 87 detail routes omit the Phase 88 handoff.");
check(manifest.expected_build.static_pages >= 5050 && manifest.expected_build.public_json_exports >= 35 && manifest.expected_build.phase_88_job_access_matching_hiring_nondiscrimination_dossiers === 8 && manifest.expected_build.phase_88_job_quality_wages_benefits_hours_safety_ledgers === 8 && manifest.expected_build.phase_88_worker_voice_organizing_collective_bargaining_economic_democracy_registers === 8 && manifest.expected_build.phase_88_livelihood_security_displacement_just_transition_long_horizon_ledgers === 8 && manifest.expected_build.phase_88_synthetic_cases === 2560, "The release manifest omits Phase 88 counts.");
check(manifest.job_access_matching_hiring_nondiscrimination_routes?.length === 8 && manifest.job_quality_wages_benefits_hours_safety_routes?.length === 8 && manifest.worker_voice_organizing_collective_bargaining_economic_democracy_routes?.length === 8 && manifest.livelihood_security_displacement_just_transition_long_horizon_routes?.length === 8, "The release manifest omits Phase 88 routes.");
check(await exists(workspaceRoot, "docs", "work-packages", "phase-88-work-labor-livelihoods-economic-democracy.md"), "The Phase 88 work package is missing.");

if (failures.length) {
  console.error(`Phase 88 assertions failed with ${failures.length} issue(s):`);
  failures.forEach((failure) => console.error(`- ${failure}`));
  process.exit(1);
}
console.log("Phase 88 assertions passed: 8 inactive job-access dossiers, 8 inactive job-quality ledgers, 8 inactive worker-voice registers, 8 inactive livelihood ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 job, hiring, quality, bargaining, livelihood, transition, score, ranking, or Phase 64 decisions.");
