import { readFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-86-health-public-health-disability-population-wellbeing-registry.json");
const phase85 = await readJson(appRoot, "src", "data", "phase-85-housing-shelter-land-use-place-stability-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const accessRecords = registry.primary_preventive_community_care_access_dossiers;
const careRecords = registry.acute_emergency_specialty_behavioral_health_care_ledgers;
const publicHealthRecords = registry.public_health_surveillance_prevention_environmental_exposure_registers;
const wellbeingRecords = registry.disability_equity_preparedness_population_wellbeing_ledgers;
check(registry.schema_version === "1.0" && registry.phase === "86", "The Phase 86 registry identity is invalid.");
check(accessRecords.length === 8 && careRecords.length === 8 && publicHealthRecords.length === 8 && wellbeingRecords.length === 8, "Phase 86 must contain 8 records in each family.");
check(registry.access_prevention_gates.length === 20 && registry.clinical_care_gates.length === 20 && registry.public_health_gates.length === 22 && registry.population_wellbeing_gates.length === 22, "The Phase 86 gate counts must be 20/20/22/22.");
check(registry.health_access_care_settings.length === 14 && registry.health_access_affordability_dimensions.length === 12 && registry.prevention_primary_care_safeguards.length === 12 && registry.acute_specialty_service_classes.length === 14 && registry.clinical_quality_safety_dimensions.length === 12 && registry.health_workforce_continuity_safeguards.length === 12 && registry.public_health_functions.length === 14 && registry.surveillance_governance_safeguards.length === 12 && registry.environmental_occupational_exposure_dimensions.length === 12 && registry.disability_rights_support_dimensions.length === 12 && registry.emergency_preparedness_capabilities.length === 12 && registry.population_wellbeing_equity_dimensions.length === 12 && registry.long_horizon_population_health_tests.length === 12, "The Phase 86 taxonomies are incomplete.");

const upstreamByCohort = new Map(phase85.retrofit_climate_disaster_reconstruction_place_stability_ledgers.map((record) => [record.cohort_id, record]));
for (let index = 0; index < 8; index += 1) {
  const a = accessRecords[index], c = careRecords[index], p = publicHealthRecords[index], w = wellbeingRecords[index], upstream = upstreamByCohort.get(a.cohort_id);
  check(Boolean(upstream) && a.retrofit_climate_disaster_reconstruction_place_stability_ledger_id === upstream.retrofit_climate_disaster_reconstruction_place_stability_ledger_id, `${a.primary_preventive_community_care_access_dossier_id} has the wrong Phase 85 predecessor.`);
  check(a.access_checks.length === 20 && a.access_checks.every((item) => item.decision_state === "Inactive") && a.access_state.startsWith("Inactive") && a.access_decision === "Not Open", `${a.primary_preventive_community_care_access_dossier_id} is not inactive.`);
  check(a.health_access_care_setting_records.length === 14 && a.health_access_care_setting_records.every((item) => item.access_state === "Unassessed") && a.health_access_affordability_dimension_records.length === 12 && a.health_access_affordability_dimension_records.every((item) => item.dimension_state === "Not Measured") && a.prevention_primary_care_safeguard_records.length === 12 && a.prevention_primary_care_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${a.primary_preventive_community_care_access_dossier_id} has an assigned taxonomy.`);
  check(c.primary_preventive_community_care_access_dossier_id === a.primary_preventive_community_care_access_dossier_id && c.care_checks.length === 20 && c.care_checks.every((item) => item.decision_state === "Inactive") && c.care_state.startsWith("Inactive") && c.care_decision === "Not Open", `${c.acute_emergency_specialty_behavioral_health_care_ledger_id} is not inactive.`);
  check(c.acute_specialty_service_class_records.length === 14 && c.acute_specialty_service_class_records.every((item) => item.service_state === "Unassessed") && c.clinical_quality_safety_dimension_records.length === 12 && c.clinical_quality_safety_dimension_records.every((item) => item.dimension_state === "Not Measured") && c.health_workforce_continuity_safeguard_records.length === 12 && c.health_workforce_continuity_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${c.acute_emergency_specialty_behavioral_health_care_ledger_id} has an assigned taxonomy.`);
  check(p.acute_emergency_specialty_behavioral_health_care_ledger_id === c.acute_emergency_specialty_behavioral_health_care_ledger_id && p.public_health_checks.length === 22 && p.public_health_checks.every((item) => item.decision_state === "Inactive") && p.public_health_state.startsWith("Inactive") && p.public_health_decision === "Not Open", `${p.public_health_surveillance_prevention_environmental_exposure_register_id} is not inactive.`);
  check(p.public_health_function_records.length === 14 && p.public_health_function_records.every((item) => item.function_state === "Unassessed") && p.surveillance_governance_safeguard_records.length === 12 && p.surveillance_governance_safeguard_records.every((item) => item.safeguard_state === "Unverified") && p.environmental_occupational_exposure_dimension_records.length === 12 && p.environmental_occupational_exposure_dimension_records.every((item) => item.dimension_state === "Not Measured"), `${p.public_health_surveillance_prevention_environmental_exposure_register_id} has an assigned taxonomy.`);
  check(w.public_health_surveillance_prevention_environmental_exposure_register_id === p.public_health_surveillance_prevention_environmental_exposure_register_id && w.wellbeing_checks.length === 22 && w.wellbeing_checks.every((item) => item.decision_state === "Inactive") && w.wellbeing_state.startsWith("Inactive") && w.wellbeing_decision === "Not Open", `${w.disability_equity_preparedness_population_wellbeing_ledger_id} is not inactive.`);
  check(w.disability_rights_support_dimension_records.length === 12 && w.disability_rights_support_dimension_records.every((item) => item.dimension_state === "Unassessed") && w.emergency_preparedness_capability_records.length === 12 && w.emergency_preparedness_capability_records.every((item) => item.capability_state === "Not Tested") && w.population_wellbeing_equity_dimension_records.length === 12 && w.population_wellbeing_equity_dimension_records.every((item) => item.dimension_state === "Not Measured") && w.long_horizon_population_health_test_records.length === 12 && w.long_horizon_population_health_test_records.every((item) => item.test_state === "Not Tested"), `${w.disability_equity_preparedness_population_wellbeing_ledger_id} has an assigned taxonomy.`);
}

const taxonomyKeys = new Set(["health_access_care_setting_records", "health_access_affordability_dimension_records", "prevention_primary_care_safeguard_records", "acute_specialty_service_class_records", "clinical_quality_safety_dimension_records", "health_workforce_continuity_safeguard_records", "public_health_function_records", "surveillance_governance_safeguard_records", "environmental_occupational_exposure_dimension_records", "disability_rights_support_dimension_records", "emergency_preparedness_capability_records", "population_wellbeing_equity_dimension_records", "long_horizon_population_health_test_records"]);
for (const record of [...accessRecords, ...careRecords, ...publicHealthRecords, ...wellbeingRecords]) {
  const flat = JSON.stringify(record);
  check(!flat.includes('"propagation_status":"complete"') && !flat.includes('"phase64_cell_change":"advanced"'), `${record.slug} contains an unauthorized advance.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} has non-empty ${key}.`);
}
const countKeys = new Set(["primary_preventive_community_care_access_dossiers", "acute_emergency_specialty_behavioral_health_care_ledgers", "public_health_surveillance_prevention_environmental_exposure_registers", "disability_equity_preparedness_population_wellbeing_ledgers", "access_prevention_gates", "clinical_care_gates", "public_health_gates", "population_wellbeing_gates", "health_access_care_settings", "health_access_affordability_dimensions", "prevention_primary_care_safeguards", "acute_specialty_service_classes", "clinical_quality_safety_dimensions", "health_workforce_continuity_safeguards", "public_health_functions", "surveillance_governance_safeguards", "environmental_occupational_exposure_dimensions", "disability_rights_support_dimensions", "emergency_preparedness_capabilities", "population_wellbeing_equity_dimensions", "long_horizon_population_health_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!countKeys.has(key)) check(value === 0, `Phase 86 metric ${key} must remain zero.`);

const guideIds = ["briefing-health-population-wellbeing-doctrine-001", "briefing-primary-preventive-community-care-access-001", "briefing-acute-emergency-hospital-critical-care-001", "briefing-mental-health-substance-use-harm-reduction-001", "briefing-reproductive-maternal-newborn-child-health-001", "briefing-medicines-diagnostics-health-supply-chains-001", "briefing-public-health-surveillance-vaccination-outbreak-001", "briefing-environmental-occupational-food-water-air-health-001", "briefing-disability-rights-supports-accessible-care-001", "briefing-indigenous-rural-remote-health-jurisdiction-001", "briefing-health-workforce-quality-safety-affordability-001", "briefing-health-preparedness-recovery-population-wellbeing-001"];
const mapIds = ["dependency-map-nominal-capacity-is-not-timely-access", "dependency-map-coverage-is-not-affordable-care", "dependency-map-encounter-is-not-health-outcome", "dependency-map-surveillance-signal-is-not-diagnosis", "dependency-map-emergency-declaration-is-not-readiness", "dependency-map-service-reopening-is-not-population-recovery"];
for (const id of guideIds) check(await exists(appRoot, "src", "content", "briefings", id + ".mdx"), `${id} is missing.`);
for (const id of mapIds) check(await exists(appRoot, "src", "content", "dependency-maps", id.replace("dependency-map-", "") + ".json"), `${id} is missing.`);
for (const pathwayId of new Set(accessRecords.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 86 guides or maps.`); }
for (const record of accessRecords) check((await readText(appRoot, "src", "content", "briefings", record.canonical_briefing_id + ".mdx")).includes("## Phase 86 health and population-wellbeing boundary"), `${record.canonical_briefing_id} omits Phase 86.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 86 health, public health, disability, and population-wellbeing boundary"), `${file} omits Phase 86.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-universal-service-doctrine-001.mdx", "briefing-household-capability-doctrine-001.mdx", "briefing-community-institutions-doctrine-001.mdx", "briefing-essential-service-bundles-households-001.mdx", "briefing-disability-universal-design-home-community-001.mdx", "briefing-care-infrastructure-workforce-001.mdx", "briefing-accessibility-user-rights-remedy-001.mdx", "briefing-crisis-stabilization-recovery-001.mdx", "briefing-emergency-rationing-restoration-long-horizon-accountability-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 86 health and population-wellbeing control"), `${file} omits the Phase 86 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "health-population-wellbeing", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "health-population-wellbeing", "[id].astro") && await exists(appRoot, "src", "pages", "data", "health-public-health-disability-population-wellbeing.json.ts"), "Phase 86 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro"); check(dataIndex.includes("Health, Public Health, Disability And Population Wellbeing") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 86.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts"); check(sitemap.includes("healthWellbeingRegistry") && sitemap.includes("/evidence/health-population-wellbeing/"), "The sitemap omits Phase 86.");
const phase85Detail = await readText(appRoot, "src", "pages", "evidence", "housing-place-stability", "[id].astro"); check(phase85Detail.includes("Phase 86 Destination") && phase85Detail.includes("/evidence/health-population-wellbeing/"), "Phase 85 detail routes omit the Phase 86 handoff.");
check(manifest.expected_build.static_pages >= 4948 && manifest.expected_build.public_json_exports >= 33 && manifest.expected_build.phase_86_primary_preventive_community_care_access_dossiers === 8 && manifest.expected_build.phase_86_acute_emergency_specialty_behavioral_health_care_ledgers === 8 && manifest.expected_build.phase_86_public_health_surveillance_prevention_environmental_exposure_registers === 8 && manifest.expected_build.phase_86_disability_equity_preparedness_population_wellbeing_ledgers === 8 && manifest.expected_build.phase_86_synthetic_cases === 2560, "The release manifest omits Phase 86 counts.");
check(manifest.primary_preventive_community_care_access_routes?.length === 8 && manifest.acute_emergency_specialty_behavioral_health_care_routes?.length === 8 && manifest.public_health_surveillance_prevention_environmental_exposure_routes?.length === 8 && manifest.disability_equity_preparedness_population_wellbeing_routes?.length === 8, "The release manifest omits Phase 86 routes.");

if (failures.length) { console.error(`Phase 86 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 86 assertions passed: 8 inactive access dossiers, 8 inactive care ledgers, 8 inactive public-health registers, 8 inactive wellbeing ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 eligibility, coverage, diagnosis, triage, restriction, classification, findings, remedies, receipts, scores, rankings, or stage changes.");
