import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-91-finance-banking-credit-capital-allocation-monetary-systems-financial-stability-registry.json");
const phase90 = await readJson(appRoot, "src", "data", "phase-90-markets-firms-competition-corporate-power-democratic-economic-governance-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const money = registry.money_payments_banking_access_settlement_dossiers;
const credit = registry.credit_underwriting_affordability_servicing_productive_allocation_ledgers;
const capital = registry.capital_markets_institutional_investment_insurance_risk_transfer_registers;
const stability = registry.monetary_policy_systemic_risk_resolution_public_guarantee_democratic_finance_ledgers;
const families = [money, credit, capital, stability];
const all = families.flat();
check(registry.schema_version === "1.0" && registry.phase === "91", "The Phase 91 registry identity is invalid.");
check(families.every((records) => records.length === 8), "Phase 91 must contain eight records in each family.");
check(registry.money_gates.length === 20 && registry.credit_gates.length === 20 && registry.capital_gates.length === 22 && registry.stability_gates.length === 22, "The Phase 91 gate counts must be 20/20/22/22.");
check(registry.money_payment_monetary_forms.length === 14 && registry.banking_access_operational_dimensions.length === 12 && registry.custody_settlement_data_safeguards.length === 12 && registry.credit_instrument_borrower_classes.length === 14 && registry.credit_underwriting_servicing_dimensions.length === 12 && registry.credit_affordability_fairness_safeguards.length === 12 && registry.capital_market_institution_classes.length === 14 && registry.allocation_valuation_liquidity_dimensions.length === 12 && registry.fiduciary_insurance_risk_transfer_safeguards.length === 12 && registry.monetary_stability_institutions.length === 12 && registry.transmission_systemic_risk_dimensions.length === 12 && registry.intervention_resolution_due_process_safeguards.length === 12 && registry.long_horizon_financial_system_tests.length === 12, "The Phase 91 controlled taxonomies are incomplete.");
check(["account access is not financial inclusion", "credit availability is not productive allocation", "asset-price growth is not durable wealth", "capitalization is not resilience", "central-bank intervention is not distributional legitimacy", "financial innovation is not financial stability"].every((boundary) => registry.interpretation_boundary.toLowerCase().includes(boundary)), "The Phase 91 non-substitution boundary is incomplete.");

const upstream = new Map(phase90.democratic_economic_governance_rights_remedy_long_horizon_ledgers.map((record) => [record.cohort_id, record]));
const taxonomyKeys = new Set(["money_payment_monetary_form_records", "banking_access_operational_dimension_records", "custody_settlement_data_safeguard_records", "credit_instrument_borrower_class_records", "credit_underwriting_servicing_dimension_records", "credit_affordability_fairness_safeguard_records", "capital_market_institution_class_records", "allocation_valuation_liquidity_dimension_records", "fiduciary_insurance_risk_transfer_safeguard_records", "monetary_stability_institution_records", "transmission_systemic_risk_dimension_records", "intervention_resolution_due_process_safeguard_records", "long_horizon_financial_system_test_records"]);
for (let index = 0; index < 8; index += 1) {
  const m = money[index], c = credit[index], k = capital[index], s = stability[index], u = upstream.get(m.cohort_id);
  check(Boolean(u) && m.democratic_economic_governance_rights_remedy_long_horizon_ledger_id === u.democratic_economic_governance_rights_remedy_long_horizon_ledger_id, `${m.slug} has the wrong Phase 90 predecessor.`);
  check(m.money_state === "Inactive - No Verified Phase 90 Democratic-Economic-Governance Record" && m.money_decision === "Not Open" && m.money_checks.length === 20 && m.money_checks.every((x) => x.decision_state === "Inactive"), `${m.slug} is not inactive.`);
  check(m.money_payment_monetary_form_records.length === 14 && m.money_payment_monetary_form_records.every((x) => x.form_state === "Unassessed") && m.banking_access_operational_dimension_records.length === 12 && m.banking_access_operational_dimension_records.every((x) => x.dimension_state === "Not Measured") && m.custody_settlement_data_safeguard_records.length === 12 && m.custody_settlement_data_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${m.slug} has an invalid money taxonomy.`);
  check(c.money_payments_banking_access_settlement_dossier_id === m.money_payments_banking_access_settlement_dossier_id && c.credit_state === "Inactive - No Adopted Money Payments Banking And Settlement Baseline" && c.credit_decision === "Not Open" && c.credit_checks.length === 20 && c.credit_checks.every((x) => x.decision_state === "Inactive"), `${c.slug} is not inactive.`);
  check(c.credit_instrument_borrower_class_records.length === 14 && c.credit_instrument_borrower_class_records.every((x) => x.class_state === "Unassessed") && c.credit_underwriting_servicing_dimension_records.length === 12 && c.credit_underwriting_servicing_dimension_records.every((x) => x.dimension_state === "Not Measured") && c.credit_affordability_fairness_safeguard_records.length === 12 && c.credit_affordability_fairness_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${c.slug} has an invalid credit taxonomy.`);
  check(k.credit_underwriting_affordability_servicing_productive_allocation_ledger_id === c.credit_underwriting_affordability_servicing_productive_allocation_ledger_id && k.capital_state === "Inactive - No Verified Credit Underwriting Affordability And Allocation Baseline" && k.capital_decision === "Not Open" && k.capital_checks.length === 22 && k.capital_checks.every((x) => x.decision_state === "Inactive"), `${k.slug} is not inactive.`);
  check(k.capital_market_institution_class_records.length === 14 && k.capital_market_institution_class_records.every((x) => x.class_state === "Unassessed") && k.allocation_valuation_liquidity_dimension_records.length === 12 && k.allocation_valuation_liquidity_dimension_records.every((x) => x.dimension_state === "Not Measured") && k.fiduciary_insurance_risk_transfer_safeguard_records.length === 12 && k.fiduciary_insurance_risk_transfer_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${k.slug} has an invalid capital taxonomy.`);
  check(s.capital_markets_institutional_investment_insurance_risk_transfer_register_id === k.capital_markets_institutional_investment_insurance_risk_transfer_register_id && s.stability_state === "Inactive - No Verified Capital-Market Insurance And Risk-Transfer Baseline" && s.stability_decision === "Not Open" && s.stability_checks.length === 22 && s.stability_checks.every((x) => x.decision_state === "Inactive"), `${s.slug} is not inactive.`);
  check(s.monetary_stability_institution_records.length === 12 && s.monetary_stability_institution_records.every((x) => x.institution_state === "Unassessed") && s.transmission_systemic_risk_dimension_records.length === 12 && s.transmission_systemic_risk_dimension_records.every((x) => x.dimension_state === "Not Measured") && s.intervention_resolution_due_process_safeguard_records.length === 12 && s.intervention_resolution_due_process_safeguard_records.every((x) => x.safeguard_state === "Unverified") && s.long_horizon_financial_system_test_records.length === 12 && s.long_horizon_financial_system_test_records.every((x) => x.test_state === "Not Tested"), `${s.slug} has an invalid stability taxonomy.`);
}
for (const record of all) {
  check(record.propagation_status === "not_started" && record.first_reviewer_id === null && record.second_reviewer_id === null && record.phase64_cell_change === "none", `${record.slug} contains a premature review or advance.`);
  for (const [key, value] of Object.entries(record)) {
    if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
    if (key.endsWith("_receipt_id")) check(value === null, `${record.slug} contains ${key}.`);
    if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} contains non-taxonomy ${key}.`);
  }
}
for (const key of ["verified_phase90_governance_records_received", "money_payment_or_banking_access_findings", "credit_underwriting_or_allocation_decisions", "capital_market_insurance_or_risk_transfer_decisions", "monetary_policy_stability_resolution_or_guarantee_decisions", "independent_reviews_completed", "receipts_created", "scores_created", "rankings_created", "phase64_cells_advanced"]) check(registry.metrics[key] === 0, `Phase 91 metric ${key} must remain zero.`);

const guides = ["finance-banking-credit-capital-allocation-monetary-systems-financial-stability-doctrine-001", "money-units-cash-deposits-digital-currency-001", "payment-clearing-settlement-custody-continuity-001", "banking-deposits-accounts-inclusion-public-options-001", "credit-underwriting-pricing-servicing-collections-001", "household-debt-mortgages-bankruptcy-fresh-start-001", "business-project-credit-productive-allocation-additionality-001", "capital-markets-securities-valuation-liquidity-ownership-001", "asset-management-pensions-fiduciary-stewardship-001", "insurance-risk-transfer-reinsurance-catastrophe-001", "central-banks-monetary-policy-transmission-distribution-001", "financial-stability-leverage-liquidity-resolution-public-guarantees-001"];
const maps = ["account-access-is-not-financial-inclusion", "credit-availability-is-not-productive-allocation", "asset-price-growth-is-not-durable-wealth", "capitalization-is-not-resilience", "central-bank-intervention-is-not-distributional-legitimacy", "financial-innovation-is-not-financial-stability"];
for (const slug of guides) check(await exists(appRoot, "src", "content", "briefings", `briefing-${slug}.mdx`), `Phase 91 guide ${slug} is missing.`);
for (const slug of maps) check(await exists(appRoot, "src", "content", "dependency-maps", `${slug}.json`), `Phase 91 map ${slug} is missing.`);
const guideIds = guides.map((slug) => `briefing-${slug}`), mapIds = maps.map((slug) => `dependency-map-${slug}`);
for (const pathwayId of new Set(money.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 91 content.`); }
for (const id of new Set(money.map((record) => record.canonical_briefing_id))) check((await readText(appRoot, "src", "content", "briefings", `${id}.mdx`)).includes("## Phase 91 finance, banking, credit, capital-allocation, monetary-systems, and financial-stability boundary"), `${id} omits Phase 91.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 91 finance, banking, credit, capital-allocation, monetary-systems, and financial-stability boundary"), `${file} omits Phase 91.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-public-investment-doctrine-001.mdx", "briefing-procurement-vendor-lockin-public-options-001.mdx", "briefing-public-wealth-balance-sheet-001.mdx", "briefing-cooperatives-employee-ownership-public-employment-001.mdx", "briefing-worker-voice-organizing-collective-bargaining-001.mdx", "briefing-platform-gig-informal-contingent-work-001.mdx", "briefing-distributional-public-balance-sheets-001.mdx", "briefing-community-wealth-universal-supports-public-options-001.mdx", "briefing-cross-case-public-authority-001.mdx", "briefing-shared-public-value-allocation-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 91 finance, banking, credit, capital allocation, monetary systems, and financial-stability control"), `${file} omits Phase 91 control.`);

check(await exists(appRoot, "src", "pages", "evidence", "finance-banking-credit-financial-stability", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "finance-banking-credit-financial-stability", "[id].astro") && await exists(appRoot, "src", "pages", "data", "finance-banking-credit-capital-allocation-monetary-systems-financial-stability.json.ts"), "Phase 91 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Finance, Banking, Credit, Capital Allocation, Monetary Systems And Financial Stability") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 91.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("financeBankingCreditStabilityRegistry") && sitemap.includes("/evidence/finance-banking-credit-financial-stability/"), "The sitemap omits Phase 91.");
const phase90Detail = await readText(appRoot, "src", "pages", "evidence", "markets-firms-economic-governance", "[id].astro");
check(phase90Detail.includes("Phase 91 Destination") && phase90Detail.includes("/evidence/finance-banking-credit-financial-stability/"), "Phase 90 detail routes omit the Phase 91 handoff.");
check(manifest.expected_build.static_pages >= 5203 && manifest.expected_build.public_json_exports >= 38 && manifest.expected_build.phase_91_money_payments_banking_access_settlement_dossiers === 8 && manifest.expected_build.phase_91_credit_underwriting_affordability_servicing_productive_allocation_ledgers === 8 && manifest.expected_build.phase_91_capital_markets_institutional_investment_insurance_risk_transfer_registers === 8 && manifest.expected_build.phase_91_monetary_policy_systemic_risk_resolution_public_guarantee_democratic_finance_ledgers === 8 && manifest.expected_build.phase_91_synthetic_cases === 2560, "The release manifest omits Phase 91 counts.");
check(manifest.money_payments_banking_access_settlement_routes?.length === 8 && manifest.credit_underwriting_affordability_servicing_productive_allocation_routes?.length === 8 && manifest.capital_markets_institutional_investment_insurance_risk_transfer_routes?.length === 8 && manifest.monetary_policy_systemic_risk_resolution_public_guarantee_democratic_finance_routes?.length === 8, "The release manifest omits Phase 91 routes.");
check(await exists(workspaceRoot, "docs", "work-packages", "phase-91-finance-banking-credit-capital-allocation-monetary-systems-financial-stability.md"), "The Phase 91 work package is missing.");

if (failures.length) { console.error(`Phase 91 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 91 assertions passed: 8 inactive money dossiers, 8 inactive credit ledgers, 8 inactive capital registers, 8 inactive stability ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 access, credit, allocation, investment, insurance, intervention, guarantee, resolution, score, ranking, or Phase 64 decisions.");
