import { readFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readText = async (...parts) => readFile(join(...parts), "utf8");
const readJson = async (...parts) => JSON.parse(await readText(...parts));
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };
const isEmpty = (value) => Array.isArray(value) ? value.length === 0 : value && typeof value === "object" ? Object.keys(value).length === 0 : value === null || value === "";

const registry = await readJson(appRoot, "src", "data", "phase-80-public-investment-portfolios-transition-pathways-place-based-capacity-registry.json");
const phase79 = await readJson(appRoot, "src", "data", "phase-79-public-wealth-long-horizon-stewardship-intergenerational-balance-sheet-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const theses = registry.public_investment_mission_thesis_dossiers;
const portfolios = registry.portfolio_membership_dependency_sequence_registers;
const capacities = registry.place_based_delivery_capacity_transition_ledgers;
const realizations = registry.portfolio_stress_rebalancing_realization_ledgers;

check(registry.phase === "80" && registry.schema_version === "1.0", "Phase 80 registry identity is invalid.");
check(theses.length === 8 && portfolios.length === 8 && capacities.length === 8 && realizations.length === 8, "Phase 80 record-family counts are invalid.");
check(registry.investment_thesis_gates.length === 18 && registry.portfolio_sequence_gates.length === 20 && registry.delivery_transition_gates.length === 20 && registry.realization_gates.length === 20, "Phase 80 gate counts are invalid.");
for (const [name, expected] of [["mission_classes", 12], ["investment_instrument_classes", 12], ["portfolio_dependency_classes", 12], ["sequence_stages", 12], ["delivery_capacity_dimensions", 14], ["workforce_supplier_readiness_dimensions", 12], ["place_based_obligations", 12], ["just_transition_safeguards", 12], ["portfolio_stress_triggers", 12], ["rebalancing_actions", 10], ["public_value_realization_tests", 12]]) check(registry[name].length === expected, `Phase 80 ${name} count is invalid.`);

const all = [...theses, ...portfolios, ...capacities, ...realizations];
const ids = all.map((record) => Object.values(record).find((value) => typeof value === "string" && /^80-(IMT|PDS|PDC|PRR)-/.test(value)));
check(new Set(ids).size === 32 && new Set(all.map((record) => record.slug)).size === 32, "Phase 80 IDs or slugs are not unique.");
check(new Set(theses.map((record) => record.intergenerational_balance_sheet_stewardship_ledger_id)).size === 8, "Phase 79 stewardship records do not map one-to-one to Phase 80 theses.");
check(theses.every((record) => phase79.intergenerational_balance_sheet_stewardship_ledgers.some((item) => item.intergenerational_balance_sheet_stewardship_ledger_id === record.intergenerational_balance_sheet_stewardship_ledger_id && item.cohort_id === record.cohort_id)), "A Phase 80 thesis lacks its exact Phase 79 predecessor.");

theses.forEach((record) => {
  check(record.thesis_state === "Inactive - No Verified Phase 79 Stewardship Record" && record.admission_decision === "Not Open", `${record.public_investment_mission_thesis_dossier_id} is not inactive.`);
  check(record.investment_thesis_checks.length === 18 && record.investment_thesis_checks.every((item) => item.decision_state === "Inactive"), `${record.public_investment_mission_thesis_dossier_id} has an active gate.`);
  check(record.mission_class_records.length === 12 && record.mission_class_records.every((item) => item.mission_state === "Unassigned" && isEmpty(item.evidence_ids) && isEmpty(item.authority_ids) && item.decision_id === null), `${record.public_investment_mission_thesis_dossier_id} contains an assigned mission.`);
  check(record.instrument_class_records.length === 12 && record.instrument_class_records.every((item) => item.instrument_state === "Unassessed" && isEmpty(item.funding_ids) && isEmpty(item.financing_ids) && isEmpty(item.exposure_ids)), `${record.public_investment_mission_thesis_dossier_id} contains an instrument finding.`);
  for (const field of ["verified_phase79_stewardship_record_ids", "alternative_records", "existing_asset_capability_records", "distribution_records", "resource_boundary_records", "delivery_capacity_records", "funding_records", "financing_records", "option_value_records"]) check(isEmpty(record[field]), `${record.public_investment_mission_thesis_dossier_id} contains premature ${field}.`);
  for (const field of ["mission_record", "public_need_record", "no_action_baseline_record", "investment_thesis_record", "additionality_record", "first_reviewer_id", "second_reviewer_id", "thesis_receipt_id"]) check(record[field] === null, `${record.public_investment_mission_thesis_dossier_id} contains premature ${field}.`);
  check(record.announcement_as_investment_thesis_allowed === false && record.financing_as_funding_allowed === false && record.urgency_as_priority_allowed === false && record.automatic_mission_selection_allowed === false && record.automatic_project_selection_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.public_investment_mission_thesis_dossier_id} violates an automation boundary.`);
});

portfolios.forEach((record, index) => {
  check(record.portfolio_state === "Inactive - No Admitted Investment Thesis" && record.membership_decision === "Not Open" && record.public_investment_mission_thesis_dossier_id === theses[index].public_investment_mission_thesis_dossier_id, `${record.portfolio_membership_dependency_sequence_register_id} is not inactive or linked.`);
  check(record.portfolio_sequence_checks.length === 20 && record.portfolio_sequence_checks.every((item) => item.decision_state === "Inactive"), `${record.portfolio_membership_dependency_sequence_register_id} has an active gate.`);
  check(record.dependency_class_records.length === 12 && record.dependency_class_records.every((item) => item.dependency_state === "Unmapped" && isEmpty(item.predecessor_ids) && isEmpty(item.successor_ids) && isEmpty(item.evidence_ids)), `${record.portfolio_membership_dependency_sequence_register_id} contains a dependency.`);
  check(record.sequence_stage_records.length === 12 && record.sequence_stage_records.every((item) => item.stage_state === "Unscheduled" && isEmpty(item.member_ids) && isEmpty(item.entry_receipt_ids) && isEmpty(item.exit_receipt_ids)), `${record.portfolio_membership_dependency_sequence_register_id} contains a sequence.`);
  for (const field of ["candidate_member_records", "admitted_member_records", "excluded_member_records", "nonproject_member_records", "dependency_records", "critical_path_records", "sequencing_records", "stage_gate_records", "option_records", "funding_mix_records", "financing_mix_records", "affordability_records", "concurrent_capacity_records", "resource_allocation_records", "distribution_records", "transition_obligation_records", "interface_records", "conflict_and_recusal_records"]) check(isEmpty(record[field]), `${record.portfolio_membership_dependency_sequence_register_id} contains premature ${field}.`);
  check(record.portfolio_charter_record === null && record.first_reviewer_id === null && record.second_reviewer_id === null && record.portfolio_receipt_id === null, `${record.portfolio_membership_dependency_sequence_register_id} contains a premature decision.`);
  check(record.project_list_as_portfolio_allowed === false && record.earliest_ready_as_priority_allowed === false && record.automatic_membership_allowed === false && record.automatic_sequence_allowed === false && record.automatic_funding_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.portfolio_membership_dependency_sequence_register_id} violates an automation boundary.`);
});

capacities.forEach((record, index) => {
  check(record.delivery_state === "Inactive - No Authorized Portfolio Sequence" && record.readiness_decision === "Not Open" && record.portfolio_membership_dependency_sequence_register_id === portfolios[index].portfolio_membership_dependency_sequence_register_id, `${record.place_based_delivery_capacity_transition_ledger_id} is not inactive or linked.`);
  check(record.delivery_transition_checks.length === 20 && record.delivery_transition_checks.every((item) => item.decision_state === "Inactive"), `${record.place_based_delivery_capacity_transition_ledger_id} has an active gate.`);
  check(record.delivery_capacity_dimension_records.length === 14 && record.delivery_capacity_dimension_records.every((item) => item.capacity_state === "Untested" && isEmpty(item.baseline_ids) && isEmpty(item.gap_ids) && isEmpty(item.owner_ids)), `${record.place_based_delivery_capacity_transition_ledger_id} contains a capacity finding.`);
  check(record.workforce_supplier_readiness_records.length === 12 && record.workforce_supplier_readiness_records.every((item) => item.readiness_state === "Unverified" && isEmpty(item.workforce_ids) && isEmpty(item.supplier_ids)), `${record.place_based_delivery_capacity_transition_ledger_id} contains readiness.`);
  check(record.place_based_obligation_records.length === 12 && record.place_based_obligation_records.every((item) => item.obligation_state === "Unassigned" && isEmpty(item.place_ids) && isEmpty(item.owner_ids) && isEmpty(item.remedy_ids)), `${record.place_based_delivery_capacity_transition_ledger_id} contains a place obligation.`);
  check(record.just_transition_safeguard_records.length === 12 && record.just_transition_safeguard_records.every((item) => item.safeguard_state === "Unverified" && isEmpty(item.affected_public_ids) && isEmpty(item.funding_ids) && isEmpty(item.receipt_ids)), `${record.place_based_delivery_capacity_transition_ledger_id} contains a transition safeguard.`);
  for (const field of ["accountable_owner_records", "institutional_baseline_records", "program_management_records", "procurement_capacity_records", "workforce_records", "supplier_records", "public_option_capacity_records", "land_and_corridor_records", "water_records", "energy_and_grid_records", "material_and_logistics_records", "housing_and_service_records", "place_distribution_records", "transition_plan_records", "community_agreement_records", "operating_readiness_records", "capacity_trigger_records"]) check(isEmpty(record[field]), `${record.place_based_delivery_capacity_transition_ledger_id} contains premature ${field}.`);
  check(record.first_reviewer_id === null && record.second_reviewer_id === null && record.capacity_receipt_id === null && record.local_spend_as_just_transition_allowed === false && record.procurement_as_delivery_capacity_allowed === false && record.automatic_readiness_finding_allowed === false && record.automatic_resource_allocation_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.place_based_delivery_capacity_transition_ledger_id} violates a boundary.`);
});

realizations.forEach((record, index) => {
  check(record.realization_state === "Inactive - No Verified Delivery Baseline" && record.rebalancing_decision === "Not Open" && record.place_based_delivery_capacity_transition_ledger_id === capacities[index].place_based_delivery_capacity_transition_ledger_id, `${record.portfolio_stress_rebalancing_realization_ledger_id} is not inactive or linked.`);
  check(record.realization_checks.length === 20 && record.realization_checks.every((item) => item.decision_state === "Inactive"), `${record.portfolio_stress_rebalancing_realization_ledger_id} has an active gate.`);
  check(record.portfolio_stress_trigger_records.length === 12 && record.portfolio_stress_trigger_records.every((item) => item.trigger_state === "Dormant" && isEmpty(item.event_ids) && item.review_id === null && item.decision_id === null), `${record.portfolio_stress_rebalancing_realization_ledger_id} contains stress.`);
  check(record.rebalancing_action_records.length === 10 && record.rebalancing_action_records.every((item) => item.action_state === "Not Considered" && isEmpty(item.member_ids) && isEmpty(item.condition_ids) && item.decision_id === null), `${record.portfolio_stress_rebalancing_realization_ledger_id} contains rebalancing.`);
  check(record.public_value_realization_test_records.length === 12 && record.public_value_realization_test_records.every((item) => item.test_state === "Not Tested" && isEmpty(item.output_ids) && isEmpty(item.outcome_ids) && item.finding_id === null), `${record.portfolio_stress_rebalancing_realization_ledger_id} contains realized value.`);
  for (const field of ["scenario_records", "concentration_records", "stress_test_records", "observed_trigger_records", "option_records", "off_ramp_records", "rebalancing_records", "finance_consequence_records", "capacity_consequence_records", "place_transition_consequence_records", "public_option_records", "verified_output_records", "observed_outcome_records", "public_value_findings", "corrective_action_records", "portfolio_learning_records"]) check(isEmpty(record[field]), `${record.portfolio_stress_rebalancing_realization_ledger_id} contains premature ${field}.`);
  check(record.frozen_thesis_record === null && record.first_reviewer_id === null && record.second_reviewer_id === null && record.realization_receipt_id === null && record.rebalancing_as_failure_erasure_allowed === false && record.delivered_output_as_realized_value_allowed === false && record.automatic_rebalancing_allowed === false && record.automatic_outcome_finding_allowed === false && record.automatic_score_allowed === false && record.automatic_rank_allowed === false && record.phase64_cell_change === "none", `${record.portfolio_stress_rebalancing_realization_ledger_id} violates a boundary.`);
});

const nonZeroMetrics = new Set(["public_investment_mission_thesis_dossiers", "portfolio_membership_dependency_sequence_registers", "place_based_delivery_capacity_transition_ledgers", "portfolio_stress_rebalancing_realization_ledgers", "investment_thesis_gates", "portfolio_sequence_gates", "delivery_transition_gates", "realization_gates", "mission_classes", "investment_instrument_classes", "portfolio_dependency_classes", "sequence_stages", "delivery_capacity_dimensions", "workforce_supplier_readiness_dimensions", "place_based_obligations", "just_transition_safeguards", "portfolio_stress_triggers", "rebalancing_actions", "public_value_realization_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!nonZeroMetrics.has(key)) check(value === 0, `Phase 80 metric ${key} must remain zero.`);

const guideIds = ["briefing-public-investment-doctrine-001", "briefing-mission-thesis-public-purpose-001", "briefing-portfolio-construction-without-ranking-001", "briefing-dependency-capital-sequencing-001", "briefing-public-funding-versus-financing-001", "briefing-delivery-institutions-owner-capacity-001", "briefing-workforce-supplier-readiness-001", "briefing-land-water-energy-infrastructure-constraints-001", "briefing-place-based-value-just-transition-001", "briefing-option-preservation-stage-gates-offramps-001", "briefing-portfolio-stress-rebalancing-concentration-001", "briefing-public-value-realization-transition-accountability-001"];
for (const id of guideIds) {
  const body = await readText(appRoot, "src", "content", "briefings", id + ".mdx");
  check(body.includes('record_status: "Published"') && body.length > 8000 && body.includes("## Public contract"), `${id} is missing, short, or not Published.`);
}
const mapSlugs = ["project-list-is-not-investment-portfolio", "funding-is-not-financing-capacity", "earliest-ready-is-not-highest-public-priority", "procurement-capacity-is-not-delivery-capacity", "local-expenditure-is-not-just-transition", "delivered-output-is-not-realized-public-value"];
const mapIds = [];
for (const slug of mapSlugs) { const map = await readJson(appRoot, "src", "content", "dependency-maps", slug + ".json"); mapIds.push(map.id); check(map.record_status === "Published" && map.nodes.length === 7 && map.links.length === 6 && map.interpretation_boundary.includes("does not establish"), `${slug} is invalid.`); }
const pathwayIds = [...new Set(theses.flatMap((record) => record.reader_pathway_ids))];
check(pathwayIds.length === 10, `Expected 10 pathway integrations, found ${pathwayIds.length}.`);
for (const pathwayId of pathwayIds) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 80 guides or maps.`); }
for (const record of theses) check((await readText(appRoot, "src", "content", "briefings", record.canonical_briefing_id + ".mdx")).includes("## Phase 80 public-investment portfolio and transition boundary"), `${record.canonical_briefing_id} omits Phase 80.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 80 public-investment, capacity, and transition boundary"), `${file} omits Phase 80.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-implementation-commitment-ledger-001.mdx", "briefing-realized-impact-audit-001.mdx", "briefing-institutional-memory-negative-results-001.mdx", "briefing-policy-retirement-decommissioning-001.mdx", "briefing-fiscal-capacity-contribution-sharing-001.mdx", "briefing-public-wealth-balance-sheet-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 80 portfolio, capacity, transition, and realization control"), `${file} omits the Phase 80 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "investment-portfolios", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "investment-portfolios", "[id].astro") && await exists(appRoot, "src", "pages", "data", "public-investment-portfolios-transition-capacity.json.ts"), "Phase 80 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Public Investment Portfolios And Transition Capacity") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 80.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("investmentPortfolioRegistry") && sitemap.includes("/evidence/investment-portfolios/"), "The sitemap omits Phase 80.");
const phase79Detail = await readText(appRoot, "src", "pages", "evidence", "stewardship", "[id].astro");
check(phase79Detail.includes("Phase 80 Destination") && phase79Detail.includes("/evidence/investment-portfolios/"), "Phase 79 detail routes omit the Phase 80 handoff.");
check(manifest.expected_build.static_pages >= 4642 && manifest.expected_build.public_json_exports >= 27 && manifest.expected_build.phase_80_public_investment_mission_thesis_dossiers === 8 && manifest.expected_build.phase_80_portfolio_membership_dependency_sequence_registers === 8 && manifest.expected_build.phase_80_place_based_delivery_capacity_transition_ledgers === 8 && manifest.expected_build.phase_80_portfolio_stress_rebalancing_realization_ledgers === 8 && manifest.expected_build.phase_80_synthetic_cases === 2560, "The release manifest omits Phase 80 counts.");
check(manifest.public_investment_mission_thesis_routes?.length === 8 && manifest.portfolio_membership_dependency_sequence_routes?.length === 8 && manifest.place_based_delivery_capacity_transition_routes?.length === 8 && manifest.portfolio_stress_rebalancing_realization_routes?.length === 8, "The release manifest omits Phase 80 routes.");

if (failures.length) { console.error(`Phase 80 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 80 assertions passed: 8 inactive investment theses, 8 inactive portfolio-sequence registers, 8 inactive place-capacity-transition ledgers, 8 inactive stress-rebalancing-realization ledgers, 78 gates per chain, 12 mission classes, 12 instrument classes, 12 dependency classes, 12 sequence stages, 14 capacity dimensions, 12 readiness dimensions, 12 place obligations, 12 transition safeguards, 12 stress triggers, 10 rebalancing actions, 12 realization tests, 10 pathways, and 0 selections, priorities, funding, financing, allocations, findings, receipts, scores, rankings, or stage changes.");
