import { readFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-84-food-systems-local-provisioning-community-resource-security-registry.json");
const phase83 = await readJson(appRoot, "src", "data", "phase-83-community-institutions-social-infrastructure-collective-resilience-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const production = registry.food_production_land_water_sovereignty_dossiers;
const provisioning = registry.processing_storage_distribution_local_provisioning_ledgers;
const foodAccess = registry.food_access_affordability_nutrition_institutional_meals_registers;
const security = registry.reserve_contamination_circularity_community_resource_security_ledgers;
check(registry.schema_version === "1.0" && registry.phase === "84", "The Phase 84 registry identity is invalid.");
check(production.length === 8 && provisioning.length === 8 && foodAccess.length === 8 && security.length === 8, "Phase 84 must contain 8 records in each family.");
check(registry.production_gates.length === 20 && registry.provisioning_gates.length === 20 && registry.food_access_gates.length === 22 && registry.resource_security_gates.length === 22, "The Phase 84 gate counts must be 20/20/22/22.");
check(registry.food_production_system_types.length === 14 && registry.land_access_tenure_stewardship_safeguards.length === 12 && registry.water_energy_climate_dependency_tests.length === 12 && registry.processing_storage_distribution_modes.length === 14 && registry.local_procurement_community_benefit_dimensions.length === 12 && registry.food_workforce_logistics_safeguards.length === 12 && registry.food_access_channels.length === 14 && registry.affordability_nutrition_dignity_dimensions.length === 12 && registry.institutional_meal_community_provisioning_safeguards.length === 12 && registry.emergency_reserve_capabilities.length === 12 && registry.contamination_biosecurity_safeguards.length === 12 && registry.food_waste_circular_flow_capabilities.length === 12 && registry.long_horizon_community_resource_security_tests.length === 12, "The Phase 84 taxonomies are incomplete.");

const upstreamByCohort = new Map(phase83.collective_preparedness_trauma_recovery_resilience_ledgers.map((record) => [record.cohort_id, record]));
for (let index = 0; index < 8; index += 1) {
  const p = production[index], l = provisioning[index], a = foodAccess[index], s = security[index], upstream = upstreamByCohort.get(p.cohort_id);
  check(Boolean(upstream) && p.collective_preparedness_trauma_recovery_resilience_ledger_id === upstream.collective_preparedness_trauma_recovery_resilience_ledger_id, `${p.food_production_land_water_sovereignty_dossier_id} has the wrong Phase 83 predecessor.`);
  check(p.production_checks.length === 20 && p.production_checks.every((item) => item.decision_state === "Inactive") && p.production_state.startsWith("Inactive") && p.production_decision === "Not Open", `${p.food_production_land_water_sovereignty_dossier_id} is not inactive.`);
  check(p.food_production_system_type_records.length === 14 && p.food_production_system_type_records.every((item) => item.production_state === "Unassessed") && p.land_access_tenure_stewardship_safeguard_records.length === 12 && p.land_access_tenure_stewardship_safeguard_records.every((item) => item.safeguard_state === "Unverified") && p.water_energy_climate_dependency_test_records.length === 12 && p.water_energy_climate_dependency_test_records.every((item) => item.test_state === "Not Tested"), `${p.food_production_land_water_sovereignty_dossier_id} has an assigned taxonomy.`);
  check(l.food_production_land_water_sovereignty_dossier_id === p.food_production_land_water_sovereignty_dossier_id && l.provisioning_checks.length === 20 && l.provisioning_checks.every((item) => item.decision_state === "Inactive") && l.provisioning_state.startsWith("Inactive") && l.provisioning_decision === "Not Open", `${l.processing_storage_distribution_local_provisioning_ledger_id} is not inactive.`);
  check(l.processing_storage_distribution_mode_records.length === 14 && l.processing_storage_distribution_mode_records.every((item) => item.mode_state === "Unassessed") && l.local_procurement_community_benefit_dimension_records.length === 12 && l.local_procurement_community_benefit_dimension_records.every((item) => item.dimension_state === "Not Measured") && l.food_workforce_logistics_safeguard_records.length === 12 && l.food_workforce_logistics_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${l.processing_storage_distribution_local_provisioning_ledger_id} has an assigned taxonomy.`);
  check(a.processing_storage_distribution_local_provisioning_ledger_id === l.processing_storage_distribution_local_provisioning_ledger_id && a.food_access_checks.length === 22 && a.food_access_checks.every((item) => item.decision_state === "Inactive") && a.access_state.startsWith("Inactive") && a.access_decision === "Not Open", `${a.food_access_affordability_nutrition_institutional_meals_register_id} is not inactive.`);
  check(a.food_access_channel_records.length === 14 && a.food_access_channel_records.every((item) => item.channel_state === "Unassessed") && a.affordability_nutrition_dignity_dimension_records.length === 12 && a.affordability_nutrition_dignity_dimension_records.every((item) => item.dimension_state === "Not Measured") && a.institutional_meal_community_provisioning_safeguard_records.length === 12 && a.institutional_meal_community_provisioning_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${a.food_access_affordability_nutrition_institutional_meals_register_id} has an assigned taxonomy.`);
  check(s.food_access_affordability_nutrition_institutional_meals_register_id === a.food_access_affordability_nutrition_institutional_meals_register_id && s.resource_security_checks.length === 22 && s.resource_security_checks.every((item) => item.decision_state === "Inactive") && s.security_state.startsWith("Inactive") && s.security_decision === "Not Open", `${s.reserve_contamination_circularity_community_resource_security_ledger_id} is not inactive.`);
  check(s.emergency_reserve_capability_records.length === 12 && s.emergency_reserve_capability_records.every((item) => item.capability_state === "Not Tested") && s.contamination_biosecurity_safeguard_records.length === 12 && s.contamination_biosecurity_safeguard_records.every((item) => item.safeguard_state === "Unverified") && s.food_waste_circular_flow_capability_records.length === 12 && s.food_waste_circular_flow_capability_records.every((item) => item.capability_state === "Not Tested") && s.long_horizon_community_resource_security_test_records.length === 12 && s.long_horizon_community_resource_security_test_records.every((item) => item.test_state === "Not Tested"), `${s.reserve_contamination_circularity_community_resource_security_ledger_id} has an assigned taxonomy.`);
}

for (const record of [...production, ...provisioning, ...foodAccess, ...security]) {
  const flat = JSON.stringify(record);
  check(!flat.includes('"propagation_status":"complete"') && !flat.includes('"phase64_cell_change":"advanced"'), `${record.slug} contains an unauthorized advance.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_records") && !["food_production_system_type_records","land_access_tenure_stewardship_safeguard_records","water_energy_climate_dependency_test_records","processing_storage_distribution_mode_records","local_procurement_community_benefit_dimension_records","food_workforce_logistics_safeguard_records","food_access_channel_records","affordability_nutrition_dignity_dimension_records","institutional_meal_community_provisioning_safeguard_records","emergency_reserve_capability_records","contamination_biosecurity_safeguard_records","food_waste_circular_flow_capability_records","long_horizon_community_resource_security_test_records"].includes(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} has non-empty ${key}.`);
}
const countKeys = new Set(["food_production_land_water_sovereignty_dossiers","processing_storage_distribution_local_provisioning_ledgers","food_access_affordability_nutrition_institutional_meals_registers","reserve_contamination_circularity_community_resource_security_ledgers","production_gates","provisioning_gates","food_access_gates","resource_security_gates","food_production_system_types","land_access_tenure_stewardship_safeguards","water_energy_climate_dependency_tests","processing_storage_distribution_modes","local_procurement_community_benefit_dimensions","food_workforce_logistics_safeguards","food_access_channels","affordability_nutrition_dignity_dimensions","institutional_meal_community_provisioning_safeguards","emergency_reserve_capabilities","contamination_biosecurity_safeguards","food_waste_circular_flow_capabilities","long_horizon_community_resource_security_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!countKeys.has(key)) check(value === 0, `Phase 84 metric ${key} must remain zero.`);

const guideIds = ["briefing-food-systems-doctrine-001", "briefing-regional-neighborhood-provisioning-001", "briefing-land-access-tenure-stewardship-001", "briefing-indigenous-food-sovereignty-001", "briefing-food-water-energy-climate-dependencies-001", "briefing-agricultural-food-workforce-001", "briefing-processing-storage-cold-chain-001", "briefing-logistics-markets-public-procurement-001", "briefing-school-institutional-meals-001", "briefing-food-affordability-nutrition-dignity-001", "briefing-emergency-reserves-community-kitchens-001", "briefing-food-waste-circularity-resource-security-001"];
const mapIds = ["dependency-map-food-availability-is-not-nutritional-access", "dependency-map-inventory-is-not-usable-reserve", "dependency-map-local-production-is-not-resilient-provisioning", "dependency-map-procurement-spend-is-not-community-benefit", "dependency-map-waste-diversion-is-not-circular-capacity", "dependency-map-short-term-distribution-is-not-durable-food-security"];
for (const id of guideIds) check(await exists(appRoot, "src", "content", "briefings", id + ".mdx"), `${id} is missing.`);
for (const id of mapIds) check(await exists(appRoot, "src", "content", "dependency-maps", id.replace("dependency-map-", "") + ".json"), `${id} is missing.`);
for (const pathwayId of new Set(production.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 84 guides or maps.`); }
for (const record of production) check((await readText(appRoot, "src", "content", "briefings", record.canonical_briefing_id + ".mdx")).includes("## Phase 84 food-systems and community-resource-security boundary"), `${record.canonical_briefing_id} omits Phase 84.`);
for (const file of ["local-us-southwest-chip-corridor.mdx","local-ontario-real-estate.mdx","local-northern-virginia-data-center-corridor.mdx","local-florida-space-coast-launch-corridor.mdx","local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 84 food systems, local provisioning, and resource security boundary"), `${file} omits Phase 84.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx","briefing-decision-accountability-desk-001.mdx","briefing-public-investment-doctrine-001.mdx","briefing-universal-service-doctrine-001.mdx","briefing-household-capability-doctrine-001.mdx","briefing-community-institutions-doctrine-001.mdx","briefing-continuity-mutual-aid-essential-systems-001.mdx","briefing-crisis-stabilization-recovery-001.mdx","briefing-shared-public-value-allocation-001.mdx","briefing-emergency-rationing-restoration-long-horizon-accountability-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 84 food-systems and community-resource-security control"), `${file} omits the Phase 84 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "food-systems", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "food-systems", "[id].astro") && await exists(appRoot, "src", "pages", "data", "food-systems-local-provisioning-community-resource-security.json.ts"), "Phase 84 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro"); check(dataIndex.includes("Food Systems And Community Resource Security") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 84.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts"); check(sitemap.includes("foodSystemsRegistry") && sitemap.includes("/evidence/food-systems/"), "The sitemap omits Phase 84.");
const phase83Detail = await readText(appRoot, "src", "pages", "evidence", "community-institutions", "[id].astro"); check(phase83Detail.includes("Phase 84 Destination") && phase83Detail.includes("/evidence/food-systems/"), "Phase 83 detail routes omit the Phase 84 handoff.");
check(manifest.expected_build.static_pages >= 4846 && manifest.expected_build.public_json_exports >= 31 && manifest.expected_build.phase_84_food_production_land_water_sovereignty_dossiers === 8 && manifest.expected_build.phase_84_processing_storage_distribution_local_provisioning_ledgers === 8 && manifest.expected_build.phase_84_food_access_affordability_nutrition_institutional_meals_registers === 8 && manifest.expected_build.phase_84_reserve_contamination_circularity_community_resource_security_ledgers === 8 && manifest.expected_build.phase_84_synthetic_cases === 2560, "The release manifest omits Phase 84 counts.");
check(manifest.food_production_land_water_sovereignty_routes?.length === 8 && manifest.processing_storage_distribution_local_provisioning_routes?.length === 8 && manifest.food_access_affordability_nutrition_institutional_meals_routes?.length === 8 && manifest.reserve_contamination_circularity_community_resource_security_routes?.length === 8, "The release manifest omits Phase 84 routes.");

if (failures.length) { console.error(`Phase 84 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 84 assertions passed: 8 inactive production dossiers, 8 inactive provisioning ledgers, 8 inactive access registers, 8 inactive security ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 allocations, findings, releases, recalls, remedies, receipts, scores, rankings, or stage changes.");
