import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-89-income-wealth-poverty-social-protection-economic-security-registry.json");
const phase88 = await readJson(appRoot, "src", "data", "phase-88-work-labor-livelihoods-economic-democracy-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const income = registry.household_income_earnings_tax_transfer_resource_dossiers;
const wealth = registry.wealth_assets_debt_liabilities_intergenerational_balance_ledgers;
const protection = registry.poverty_deprivation_social_protection_benefit_access_registers;
const security = registry.economic_security_distribution_shock_mobility_long_horizon_ledgers;
const families = [income, wealth, protection, security];
const all = families.flat();
check(registry.schema_version === "1.0" && registry.phase === "89", "The Phase 89 registry identity is invalid.");
check(families.every((records) => records.length === 8), "Phase 89 must contain eight records in each family.");
check(registry.income_gates.length === 20 && registry.wealth_gates.length === 20 && registry.protection_gates.length === 22 && registry.security_gates.length === 22, "The Phase 89 gate counts must be 20/20/22/22.");
check(registry.income_source_classes.length === 14 && registry.household_resource_adequacy_dimensions.length === 12 && registry.tax_transfer_administration_safeguards.length === 12 && registry.wealth_asset_liability_classes.length === 14 && registry.wealth_security_distribution_dimensions.length === 12 && registry.debt_insolvency_inheritance_safeguards.length === 12 && registry.poverty_material_deprivation_dimensions.length === 14 && registry.social_protection_systems.length === 12 && registry.benefit_access_rights_administration_safeguards.length === 12 && registry.economic_security_shock_response_systems.length === 12 && registry.shared_prosperity_distribution_dimensions.length === 12 && registry.intergenerational_mobility_security_safeguards.length === 12 && registry.long_horizon_economic_security_tests.length === 12, "The Phase 89 controlled taxonomies are incomplete.");
check(["income transfer is not freedom from poverty", "earnings are not household wealth", "benefit eligibility is not benefit access", "aggregate growth is not shared prosperity", "asset ownership is not economic security", "poverty exit is not durable mobility"].every((boundary) => registry.interpretation_boundary.toLowerCase().includes(boundary)), "The Phase 89 non-substitution boundary is incomplete.");

const upstream = new Map(phase88.livelihood_security_displacement_just_transition_long_horizon_ledgers.map((record) => [record.cohort_id, record]));
const taxonomyKeys = new Set(["income_source_class_records", "household_resource_adequacy_dimension_records", "tax_transfer_administration_safeguard_records", "wealth_asset_liability_class_records", "wealth_security_distribution_dimension_records", "debt_insolvency_inheritance_safeguard_records", "poverty_material_deprivation_dimension_records", "social_protection_system_records", "benefit_access_rights_administration_safeguard_records", "economic_security_shock_response_system_records", "shared_prosperity_distribution_dimension_records", "intergenerational_mobility_security_safeguard_records", "long_horizon_economic_security_test_records"]);
for (let index = 0; index < 8; index += 1) {
  const i = income[index], w = wealth[index], p = protection[index], s = security[index], u = upstream.get(i.cohort_id);
  check(Boolean(u) && i.livelihood_security_displacement_just_transition_long_horizon_ledger_id === u.livelihood_security_displacement_just_transition_long_horizon_ledger_id, `${i.slug} has the wrong Phase 88 predecessor.`);
  check(i.income_state === "Inactive - No Verified Phase 88 Livelihood-Security Record" && i.income_decision === "Not Open" && i.income_checks.length === 20 && i.income_checks.every((x) => x.decision_state === "Inactive"), `${i.slug} is not inactive.`);
  check(i.income_source_class_records.length === 14 && i.income_source_class_records.every((x) => x.source_state === "Unassessed") && i.household_resource_adequacy_dimension_records.length === 12 && i.household_resource_adequacy_dimension_records.every((x) => x.dimension_state === "Not Measured") && i.tax_transfer_administration_safeguard_records.length === 12 && i.tax_transfer_administration_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${i.slug} has an invalid income taxonomy.`);
  check(w.household_income_earnings_tax_transfer_resource_dossier_id === i.household_income_earnings_tax_transfer_resource_dossier_id && w.wealth_state === "Inactive - No Adopted Household-Income And Resource Baseline" && w.wealth_decision === "Not Open" && w.wealth_checks.length === 20 && w.wealth_checks.every((x) => x.decision_state === "Inactive"), `${w.slug} is not inactive.`);
  check(w.wealth_asset_liability_class_records.length === 14 && w.wealth_asset_liability_class_records.every((x) => x.class_state === "Unassessed") && w.wealth_security_distribution_dimension_records.every((x) => x.dimension_state === "Not Measured") && w.debt_insolvency_inheritance_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${w.slug} has an invalid wealth taxonomy.`);
  check(p.wealth_assets_debt_liabilities_intergenerational_balance_ledger_id === w.wealth_assets_debt_liabilities_intergenerational_balance_ledger_id && p.protection_state === "Inactive - No Verified Wealth And Balance-Sheet Baseline" && p.protection_decision === "Not Open" && p.protection_checks.length === 22 && p.protection_checks.every((x) => x.decision_state === "Inactive"), `${p.slug} is not inactive.`);
  check(p.poverty_material_deprivation_dimension_records.length === 14 && p.poverty_material_deprivation_dimension_records.every((x) => x.dimension_state === "Unassessed") && p.social_protection_system_records.every((x) => x.system_state === "Unassessed") && p.benefit_access_rights_administration_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${p.slug} has an invalid protection taxonomy.`);
  check(s.poverty_deprivation_social_protection_benefit_access_register_id === p.poverty_deprivation_social_protection_benefit_access_register_id && s.security_state === "Inactive - No Verified Social-Protection And Benefit-Access Baseline" && s.security_decision === "Not Open" && s.security_checks.length === 22 && s.security_checks.every((x) => x.decision_state === "Inactive"), `${s.slug} is not inactive.`);
  check(s.economic_security_shock_response_system_records.length === 12 && s.economic_security_shock_response_system_records.every((x) => x.system_state === "Unassessed") && s.shared_prosperity_distribution_dimension_records.every((x) => x.dimension_state === "Not Measured") && s.intergenerational_mobility_security_safeguard_records.every((x) => x.safeguard_state === "Unverified") && s.long_horizon_economic_security_test_records.every((x) => x.test_state === "Not Tested"), `${s.slug} has an invalid security taxonomy.`);
}
for (const record of all) {
  check(record.propagation_status === "not_started" && record.first_reviewer_id === null && record.second_reviewer_id === null && record.phase64_cell_change === "none", `${record.slug} contains a premature review or advance.`);
  for (const [key, value] of Object.entries(record)) {
    if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
    if (key.endsWith("_receipt_id")) check(value === null, `${record.slug} contains ${key}.`);
    if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} contains non-taxonomy ${key}.`);
  }
}
for (const [key, value] of Object.entries(registry.metrics)) if (!Number.isInteger(value) || key.includes("received") || key.includes("findings") || key.includes("decisions") || key.includes("completed") || key.includes("created") || key.includes("advanced")) { if (!Number.isInteger(value) || ![8,12,14,20,22].includes(value)) check(value === 0, `Phase 89 metric ${key} must remain zero.`); }

const guides = ["income-wealth-poverty-social-protection-economic-security-doctrine-001", "household-income-earnings-resources-001", "taxes-transfers-redistribution-fiscal-incidence-001", "wealth-assets-liabilities-balance-sheets-001", "debt-credit-insolvency-financial-resilience-001", "poverty-material-deprivation-persistent-hardship-001", "benefit-eligibility-take-up-denial-appeal-001", "unemployment-disability-care-child-family-protection-001", "pensions-retirement-survivor-late-life-security-001", "inflation-prices-costs-macroeconomic-shocks-001", "community-wealth-universal-supports-public-options-001", "intergenerational-mobility-distribution-shared-prosperity-001"];
const maps = ["income-transfer-is-not-freedom-from-poverty", "earnings-are-not-household-wealth", "benefit-eligibility-is-not-benefit-access", "aggregate-growth-is-not-shared-prosperity", "asset-ownership-is-not-economic-security", "poverty-exit-is-not-durable-mobility"];
for (const slug of guides) check(await exists(appRoot, "src", "content", "briefings", `briefing-${slug}.mdx`), `Phase 89 guide ${slug} is missing.`);
for (const slug of maps) check(await exists(appRoot, "src", "content", "dependency-maps", `${slug}.json`), `Phase 89 map ${slug} is missing.`);
const guideIds = guides.map((slug) => `briefing-${slug}`), mapIds = maps.map((slug) => `dependency-map-${slug}`);
for (const pathwayId of new Set(income.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 89 content.`); }
for (const id of new Set(income.map((record) => record.canonical_briefing_id))) check((await readText(appRoot, "src", "content", "briefings", `${id}.mdx`)).includes("## Phase 89 income, wealth, poverty, social-protection, and economic-security boundary"), `${id} omits Phase 89.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 89 income, wealth, poverty, social-protection, and economic-security boundary"), `${file} omits Phase 89.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-household-capability-doctrine-001.mdx", "briefing-household-affordability-arrears-debt-001.mdx", "briefing-administrative-burden-benefit-access-001.mdx", "briefing-universal-service-doctrine-001.mdx", "briefing-public-wealth-balance-sheet-001.mdx", "briefing-distributional-public-balance-sheets-001.mdx", "briefing-wages-benefits-household-livelihood-security-001.mdx", "briefing-automation-climate-industrial-transition-001.mdx", "briefing-public-investment-doctrine-001.mdx", "briefing-long-horizon-household-security-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 89 income, wealth, poverty, protection, and economic-security control"), `${file} omits Phase 89 control.`);

check(await exists(appRoot, "src", "pages", "evidence", "income-wealth-economic-security", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "income-wealth-economic-security", "[id].astro") && await exists(appRoot, "src", "pages", "data", "income-wealth-poverty-social-protection-economic-security.json.ts"), "Phase 89 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Income, Wealth, Poverty, Social Protection And Economic Security") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 89.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("incomeWealthSecurityRegistry") && sitemap.includes("/evidence/income-wealth-economic-security/"), "The sitemap omits Phase 89.");
const phase88Detail = await readText(appRoot, "src", "pages", "evidence", "work-labor-livelihoods", "[id].astro");
check(phase88Detail.includes("Phase 89 Destination") && phase88Detail.includes("/evidence/income-wealth-economic-security/"), "Phase 88 detail routes omit the Phase 89 handoff.");
check(manifest.expected_build.static_pages >= 5101 && manifest.expected_build.public_json_exports >= 36 && manifest.expected_build.phase_89_household_income_earnings_tax_transfer_resource_dossiers === 8 && manifest.expected_build.phase_89_wealth_assets_debt_liabilities_intergenerational_balance_ledgers === 8 && manifest.expected_build.phase_89_poverty_deprivation_social_protection_benefit_access_registers === 8 && manifest.expected_build.phase_89_economic_security_distribution_shock_mobility_long_horizon_ledgers === 8 && manifest.expected_build.phase_89_synthetic_cases === 2560, "The release manifest omits Phase 89 counts.");
check(manifest.household_income_earnings_tax_transfer_resource_routes?.length === 8 && manifest.wealth_assets_debt_liabilities_intergenerational_balance_routes?.length === 8 && manifest.poverty_deprivation_social_protection_benefit_access_routes?.length === 8 && manifest.economic_security_distribution_shock_mobility_long_horizon_routes?.length === 8, "The release manifest omits Phase 89 routes.");
check(await exists(workspaceRoot, "docs", "work-packages", "phase-89-income-wealth-poverty-social-protection-economic-security.md"), "The Phase 89 work package is missing.");

if (failures.length) { console.error(`Phase 89 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 89 assertions passed: 8 inactive income dossiers, 8 inactive wealth ledgers, 8 inactive protection registers, 8 inactive economic-security ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 income, wealth, poverty, benefit, distribution, mobility, score, ranking, or Phase 64 decisions.");
