import { access, readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-90-markets-firms-competition-corporate-power-democratic-economic-governance-registry.json");
const phase89 = await readJson(appRoot, "src", "data", "phase-89-income-wealth-poverty-social-protection-economic-security-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const firms = registry.firm_formation_ownership_control_governance_dossiers;
const markets = registry.market_structure_competition_pricing_conduct_ledgers;
const power = registry.corporate_power_platform_supply_chain_public_support_registers;
const governance = registry.democratic_economic_governance_rights_remedy_long_horizon_ledgers;
const families = [firms, markets, power, governance];
const all = families.flat();
check(registry.schema_version === "1.0" && registry.phase === "90", "The Phase 90 registry identity is invalid.");
check(families.every((records) => records.length === 8), "Phase 90 must contain eight records in each family.");
check(registry.firm_gates.length === 20 && registry.market_gates.length === 20 && registry.power_gates.length === 22 && registry.governance_gates.length === 22, "The Phase 90 gate counts must be 20/20/22/22.");
check(registry.enterprise_legal_ownership_forms.length === 14 && registry.firm_governance_accountability_dimensions.length === 12 && registry.firm_lifecycle_exit_safeguards.length === 12 && registry.market_transaction_structure_classes.length === 14 && registry.competition_market_power_dimensions.length === 12 && registry.price_quality_access_conduct_safeguards.length === 12 && registry.corporate_power_influence_channels.length === 14 && registry.platform_supply_chain_finance_public_support_dimensions.length === 12 && registry.corporate_disclosure_beneficial_ownership_accountability_safeguards.length === 12 && registry.democratic_economic_governance_institutions.length === 12 && registry.affected_constituency_public_value_dimensions.length === 12 && registry.intervention_remedy_due_process_safeguards.length === 12 && registry.long_horizon_market_ecosystem_tests.length === 12, "The Phase 90 controlled taxonomies are incomplete.");
check(["firm count is not a competitive market", "lower price is not complete consumer welfare", "market concentration is not proven abuse", "profit is not productive investment", "merger approval is not public benefit", "corporate disclosure is not democratic accountability"].every((boundary) => registry.interpretation_boundary.toLowerCase().includes(boundary)), "The Phase 90 non-substitution boundary is incomplete.");

const upstream = new Map(phase89.economic_security_distribution_shock_mobility_long_horizon_ledgers.map((record) => [record.cohort_id, record]));
const taxonomyKeys = new Set(["enterprise_legal_ownership_form_records", "firm_governance_accountability_dimension_records", "firm_lifecycle_exit_safeguard_records", "market_transaction_structure_class_records", "competition_market_power_dimension_records", "price_quality_access_conduct_safeguard_records", "corporate_power_influence_channel_records", "platform_supply_chain_finance_public_support_dimension_records", "corporate_disclosure_beneficial_ownership_accountability_safeguard_records", "democratic_economic_governance_institution_records", "affected_constituency_public_value_dimension_records", "intervention_remedy_due_process_safeguard_records", "long_horizon_market_ecosystem_test_records"]);
for (let index = 0; index < 8; index += 1) {
  const f = firms[index], m = markets[index], p = power[index], g = governance[index], u = upstream.get(f.cohort_id);
  check(Boolean(u) && f.economic_security_distribution_shock_mobility_long_horizon_ledger_id === u.economic_security_distribution_shock_mobility_long_horizon_ledger_id, `${f.slug} has the wrong Phase 89 predecessor.`);
  check(f.firm_state === "Inactive - No Verified Phase 89 Economic-Security Record" && f.firm_decision === "Not Open" && f.firm_checks.length === 20 && f.firm_checks.every((x) => x.decision_state === "Inactive"), `${f.slug} is not inactive.`);
  check(f.enterprise_legal_ownership_form_records.length === 14 && f.enterprise_legal_ownership_form_records.every((x) => x.form_state === "Unassessed") && f.firm_governance_accountability_dimension_records.length === 12 && f.firm_governance_accountability_dimension_records.every((x) => x.dimension_state === "Not Measured") && f.firm_lifecycle_exit_safeguard_records.length === 12 && f.firm_lifecycle_exit_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${f.slug} has an invalid firm taxonomy.`);
  check(m.firm_formation_ownership_control_governance_dossier_id === f.firm_formation_ownership_control_governance_dossier_id && m.market_state === "Inactive - No Adopted Firm-Identity Ownership And Governance Baseline" && m.market_decision === "Not Open" && m.market_checks.length === 20 && m.market_checks.every((x) => x.decision_state === "Inactive"), `${m.slug} is not inactive.`);
  check(m.market_transaction_structure_class_records.length === 14 && m.market_transaction_structure_class_records.every((x) => x.class_state === "Unassessed") && m.competition_market_power_dimension_records.length === 12 && m.competition_market_power_dimension_records.every((x) => x.dimension_state === "Not Measured") && m.price_quality_access_conduct_safeguard_records.length === 12 && m.price_quality_access_conduct_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${m.slug} has an invalid market taxonomy.`);
  check(p.market_structure_competition_pricing_conduct_ledger_id === m.market_structure_competition_pricing_conduct_ledger_id && p.power_state === "Inactive - No Verified Market-Structure Competition And Conduct Baseline" && p.power_decision === "Not Open" && p.power_checks.length === 22 && p.power_checks.every((x) => x.decision_state === "Inactive"), `${p.slug} is not inactive.`);
  check(p.corporate_power_influence_channel_records.length === 14 && p.corporate_power_influence_channel_records.every((x) => x.channel_state === "Unassessed") && p.platform_supply_chain_finance_public_support_dimension_records.length === 12 && p.platform_supply_chain_finance_public_support_dimension_records.every((x) => x.dimension_state === "Not Measured") && p.corporate_disclosure_beneficial_ownership_accountability_safeguard_records.length === 12 && p.corporate_disclosure_beneficial_ownership_accountability_safeguard_records.every((x) => x.safeguard_state === "Unverified"), `${p.slug} has an invalid power taxonomy.`);
  check(g.corporate_power_platform_supply_chain_public_support_register_id === p.corporate_power_platform_supply_chain_public_support_register_id && g.governance_state === "Inactive - No Verified Corporate-Power And Public-Accountability Baseline" && g.governance_decision === "Not Open" && g.governance_checks.length === 22 && g.governance_checks.every((x) => x.decision_state === "Inactive"), `${g.slug} is not inactive.`);
  check(g.democratic_economic_governance_institution_records.length === 12 && g.democratic_economic_governance_institution_records.every((x) => x.institution_state === "Unassessed") && g.affected_constituency_public_value_dimension_records.length === 12 && g.affected_constituency_public_value_dimension_records.every((x) => x.dimension_state === "Not Measured") && g.intervention_remedy_due_process_safeguard_records.length === 12 && g.intervention_remedy_due_process_safeguard_records.every((x) => x.safeguard_state === "Unverified") && g.long_horizon_market_ecosystem_test_records.length === 12 && g.long_horizon_market_ecosystem_test_records.every((x) => x.test_state === "Not Tested"), `${g.slug} has an invalid governance taxonomy.`);
}
for (const record of all) {
  check(record.propagation_status === "not_started" && record.first_reviewer_id === null && record.second_reviewer_id === null && record.phase64_cell_change === "none", `${record.slug} contains a premature review or advance.`);
  for (const [key, value] of Object.entries(record)) {
    if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
    if (key.endsWith("_receipt_id")) check(value === null, `${record.slug} contains ${key}.`);
    if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} contains non-taxonomy ${key}.`);
  }
}
for (const key of ["verified_phase89_economic_security_records_received", "firm_identity_or_governance_findings", "market_structure_or_competition_findings", "corporate_power_or_public_support_findings", "democratic_governance_or_public_value_decisions", "merger_or_remedy_decisions", "independent_reviews_completed", "receipts_created", "scores_created", "rankings_created", "phase64_cells_advanced"]) check(registry.metrics[key] === 0, `Phase 90 metric ${key} must remain zero.`);

const guides = ["markets-firms-competition-corporate-power-democratic-economic-governance-doctrine-001", "firm-formation-enterprise-lifecycle-001", "ownership-control-beneficial-ownership-001", "corporate-governance-boards-stakeholders-public-obligations-001", "market-structure-concentration-entry-contestability-001", "competition-monopoly-monopsony-collusion-exclusion-001", "prices-markups-profits-rents-quality-pass-through-001", "mergers-acquisitions-rollups-remedies-001", "platforms-data-algorithms-network-effects-001", "supply-chains-buyer-power-franchises-procurement-001", "enterprise-plurality-small-business-cooperatives-public-options-001", "corporate-support-accountability-rights-remedies-public-value-001"];
const maps = ["firm-count-is-not-competitive-market", "lower-price-is-not-complete-consumer-welfare", "market-concentration-is-not-proven-abuse", "profit-is-not-productive-investment", "merger-approval-is-not-public-benefit", "corporate-disclosure-is-not-democratic-accountability"];
for (const slug of guides) check(await exists(appRoot, "src", "content", "briefings", `briefing-${slug}.mdx`), `Phase 90 guide ${slug} is missing.`);
for (const slug of maps) check(await exists(appRoot, "src", "content", "dependency-maps", `${slug}.json`), `Phase 90 map ${slug} is missing.`);
const guideIds = guides.map((slug) => `briefing-${slug}`), mapIds = maps.map((slug) => `dependency-map-${slug}`);
for (const pathwayId of new Set(firms.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 90 content.`); }
for (const id of new Set(firms.map((record) => record.canonical_briefing_id))) check((await readText(appRoot, "src", "content", "briefings", `${id}.mdx`)).includes("## Phase 90 markets, firms, competition, corporate-power, and democratic-economic-governance boundary"), `${id} omits Phase 90.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 90 markets, firms, competition, corporate-power, and democratic-economic-governance boundary"), `${file} omits Phase 90.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-public-investment-doctrine-001.mdx", "briefing-procurement-vendor-lockin-public-options-001.mdx", "briefing-public-wealth-balance-sheet-001.mdx", "briefing-cooperatives-employee-ownership-public-employment-001.mdx", "briefing-worker-voice-organizing-collective-bargaining-001.mdx", "briefing-platform-gig-informal-contingent-work-001.mdx", "briefing-distributional-public-balance-sheets-001.mdx", "briefing-community-wealth-universal-supports-public-options-001.mdx", "briefing-cross-case-public-authority-001.mdx", "briefing-shared-public-value-allocation-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 90 markets, firms, competition, corporate power, and democratic-governance control"), `${file} omits Phase 90 control.`);

check(await exists(appRoot, "src", "pages", "evidence", "markets-firms-economic-governance", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "markets-firms-economic-governance", "[id].astro") && await exists(appRoot, "src", "pages", "data", "markets-firms-competition-corporate-power-democratic-economic-governance.json.ts"), "Phase 90 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro");
check(dataIndex.includes("Markets, Firms, Competition, Corporate Power And Democratic Economic Governance") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 90.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts");
check(sitemap.includes("marketsFirmsGovernanceRegistry") && sitemap.includes("/evidence/markets-firms-economic-governance/"), "The sitemap omits Phase 90.");
const phase89Detail = await readText(appRoot, "src", "pages", "evidence", "income-wealth-economic-security", "[id].astro");
check(phase89Detail.includes("Phase 90 Destination") && phase89Detail.includes("/evidence/markets-firms-economic-governance/"), "Phase 89 detail routes omit the Phase 90 handoff.");
check(manifest.expected_build.static_pages >= 5152 && manifest.expected_build.public_json_exports >= 37 && manifest.expected_build.phase_90_firm_formation_ownership_control_governance_dossiers === 8 && manifest.expected_build.phase_90_market_structure_competition_pricing_conduct_ledgers === 8 && manifest.expected_build.phase_90_corporate_power_platform_supply_chain_public_support_registers === 8 && manifest.expected_build.phase_90_democratic_economic_governance_rights_remedy_long_horizon_ledgers === 8 && manifest.expected_build.phase_90_synthetic_cases === 2560, "The release manifest omits Phase 90 counts.");
check(manifest.firm_formation_ownership_control_governance_routes?.length === 8 && manifest.market_structure_competition_pricing_conduct_routes?.length === 8 && manifest.corporate_power_platform_supply_chain_public_support_routes?.length === 8 && manifest.democratic_economic_governance_rights_remedy_long_horizon_routes?.length === 8, "The release manifest omits Phase 90 routes.");
check(await exists(workspaceRoot, "docs", "work-packages", "phase-90-markets-firms-competition-corporate-power-democratic-economic-governance.md"), "The Phase 90 work package is missing.");

if (failures.length) { console.error(`Phase 90 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 90 assertions passed: 8 inactive firm dossiers, 8 inactive market ledgers, 8 inactive corporate-power registers, 8 inactive governance ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 firm, market, power, merger, remedy, public-value, score, ranking, or Phase 64 decisions.");
