import { readFile, access } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const appRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const workspaceRoot = resolve(appRoot, "..");
const readJson = async (...parts) => JSON.parse(await readFile(join(...parts), "utf8"));
const readText = async (...parts) => readFile(join(...parts), "utf8");
const exists = async (...parts) => { try { await access(join(...parts)); return true; } catch { return false; } };
const registry = await readJson(appRoot, "src", "data", "phase-85-housing-shelter-land-use-place-stability-registry.json");
const phase84 = await readJson(appRoot, "src", "data", "phase-84-food-systems-local-provisioning-community-resource-security-registry.json");
const manifest = await readJson(workspaceRoot, "deployment", "ftfn-v0.2-build.json");
const failures = [];
const check = (condition, message) => { if (!condition) failures.push(message); };

const delivery = registry.housing_need_supply_delivery_habitability_dossiers;
const tenure = registry.tenure_affordability_public_social_community_housing_ledgers;
const stability = registry.homelessness_shelter_supportive_housing_displacement_registers;
const place = registry.retrofit_climate_disaster_reconstruction_place_stability_ledgers;
check(registry.schema_version === "1.0" && registry.phase === "85", "The Phase 85 registry identity is invalid.");
check(delivery.length === 8 && tenure.length === 8 && stability.length === 8 && place.length === 8, "Phase 85 must contain 8 records in each family.");
check(registry.housing_delivery_gates.length === 20 && registry.tenure_affordability_gates.length === 20 && registry.housing_stability_gates.length === 22 && registry.place_stability_gates.length === 22, "The Phase 85 gate counts must be 20/20/22/22.");
check(registry.housing_supply_delivery_types.length === 14 && registry.habitability_accessibility_quality_dimensions.length === 12 && registry.land_use_infrastructure_delivery_safeguards.length === 12 && registry.housing_tenure_provider_models.length === 14 && registry.household_housing_affordability_dimensions.length === 12 && registry.public_social_community_housing_safeguards.length === 12 && registry.homelessness_shelter_supportive_housing_pathways.length === 14 && registry.housing_stability_displacement_protection_dimensions.length === 12 && registry.supportive_housing_service_dignity_safeguards.length === 12 && registry.retrofit_repair_decarbonization_capabilities.length === 12 && registry.climate_disaster_housing_safeguards.length === 12 && registry.relocation_reconstruction_right_to_return_safeguards.length === 12 && registry.long_horizon_place_stability_tests.length === 12, "The Phase 85 taxonomies are incomplete.");

const upstreamByCohort = new Map(phase84.reserve_contamination_circularity_community_resource_security_ledgers.map((record) => [record.cohort_id, record]));
for (let index = 0; index < 8; index += 1) {
  const d = delivery[index], t = tenure[index], s = stability[index], p = place[index], upstream = upstreamByCohort.get(d.cohort_id);
  check(Boolean(upstream) && d.reserve_contamination_circularity_community_resource_security_ledger_id === upstream.reserve_contamination_circularity_community_resource_security_ledger_id, `${d.housing_need_supply_delivery_habitability_dossier_id} has the wrong Phase 84 predecessor.`);
  check(d.delivery_checks.length === 20 && d.delivery_checks.every((item) => item.decision_state === "Inactive") && d.delivery_state.startsWith("Inactive") && d.delivery_decision === "Not Open", `${d.housing_need_supply_delivery_habitability_dossier_id} is not inactive.`);
  check(d.housing_supply_delivery_type_records.length === 14 && d.housing_supply_delivery_type_records.every((item) => item.delivery_state === "Unassessed") && d.habitability_accessibility_quality_dimension_records.length === 12 && d.habitability_accessibility_quality_dimension_records.every((item) => item.dimension_state === "Not Measured") && d.land_use_infrastructure_delivery_safeguard_records.length === 12 && d.land_use_infrastructure_delivery_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${d.housing_need_supply_delivery_habitability_dossier_id} has an assigned taxonomy.`);
  check(t.housing_need_supply_delivery_habitability_dossier_id === d.housing_need_supply_delivery_habitability_dossier_id && t.tenure_checks.length === 20 && t.tenure_checks.every((item) => item.decision_state === "Inactive") && t.tenure_state.startsWith("Inactive") && t.tenure_decision === "Not Open", `${t.tenure_affordability_public_social_community_housing_ledger_id} is not inactive.`);
  check(t.housing_tenure_provider_model_records.length === 14 && t.housing_tenure_provider_model_records.every((item) => item.model_state === "Unassessed") && t.household_housing_affordability_dimension_records.length === 12 && t.household_housing_affordability_dimension_records.every((item) => item.dimension_state === "Not Measured") && t.public_social_community_housing_safeguard_records.length === 12 && t.public_social_community_housing_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${t.tenure_affordability_public_social_community_housing_ledger_id} has an assigned taxonomy.`);
  check(s.tenure_affordability_public_social_community_housing_ledger_id === t.tenure_affordability_public_social_community_housing_ledger_id && s.stability_checks.length === 22 && s.stability_checks.every((item) => item.decision_state === "Inactive") && s.stability_state.startsWith("Inactive") && s.stability_decision === "Not Open", `${s.homelessness_shelter_supportive_housing_displacement_register_id} is not inactive.`);
  check(s.homelessness_shelter_supportive_housing_pathway_records.length === 14 && s.homelessness_shelter_supportive_housing_pathway_records.every((item) => item.pathway_state === "Unassessed") && s.housing_stability_displacement_protection_dimension_records.length === 12 && s.housing_stability_displacement_protection_dimension_records.every((item) => item.dimension_state === "Not Measured") && s.supportive_housing_service_dignity_safeguard_records.length === 12 && s.supportive_housing_service_dignity_safeguard_records.every((item) => item.safeguard_state === "Unverified"), `${s.homelessness_shelter_supportive_housing_displacement_register_id} has an assigned taxonomy.`);
  check(p.homelessness_shelter_supportive_housing_displacement_register_id === s.homelessness_shelter_supportive_housing_displacement_register_id && p.place_checks.length === 22 && p.place_checks.every((item) => item.decision_state === "Inactive") && p.place_state.startsWith("Inactive") && p.place_decision === "Not Open", `${p.retrofit_climate_disaster_reconstruction_place_stability_ledger_id} is not inactive.`);
  check(p.retrofit_repair_decarbonization_capability_records.length === 12 && p.retrofit_repair_decarbonization_capability_records.every((item) => item.capability_state === "Not Tested") && p.climate_disaster_housing_safeguard_records.length === 12 && p.climate_disaster_housing_safeguard_records.every((item) => item.safeguard_state === "Unverified") && p.relocation_reconstruction_right_to_return_safeguard_records.length === 12 && p.relocation_reconstruction_right_to_return_safeguard_records.every((item) => item.safeguard_state === "Unverified") && p.long_horizon_place_stability_test_records.length === 12 && p.long_horizon_place_stability_test_records.every((item) => item.test_state === "Not Tested"), `${p.retrofit_climate_disaster_reconstruction_place_stability_ledger_id} has an assigned taxonomy.`);
}

const taxonomyKeys = new Set(["housing_supply_delivery_type_records", "habitability_accessibility_quality_dimension_records", "land_use_infrastructure_delivery_safeguard_records", "housing_tenure_provider_model_records", "household_housing_affordability_dimension_records", "public_social_community_housing_safeguard_records", "homelessness_shelter_supportive_housing_pathway_records", "housing_stability_displacement_protection_dimension_records", "supportive_housing_service_dignity_safeguard_records", "retrofit_repair_decarbonization_capability_records", "climate_disaster_housing_safeguard_records", "relocation_reconstruction_right_to_return_safeguard_records", "long_horizon_place_stability_test_records"]);
for (const record of [...delivery, ...tenure, ...stability, ...place]) {
  const flat = JSON.stringify(record);
  check(!flat.includes('"propagation_status":"complete"') && !flat.includes('"phase64_cell_change":"advanced"'), `${record.slug} contains an unauthorized advance.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_allowed")) check(value === false, `${record.slug} enables ${key}.`);
  for (const [key, value] of Object.entries(record)) if (key.endsWith("_records") && !taxonomyKeys.has(key)) check(Array.isArray(value) && value.length === 0, `${record.slug} has non-empty ${key}.`);
}
const countKeys = new Set(["housing_need_supply_delivery_habitability_dossiers", "tenure_affordability_public_social_community_housing_ledgers", "homelessness_shelter_supportive_housing_displacement_registers", "retrofit_climate_disaster_reconstruction_place_stability_ledgers", "housing_delivery_gates", "tenure_affordability_gates", "housing_stability_gates", "place_stability_gates", "housing_supply_delivery_types", "habitability_accessibility_quality_dimensions", "land_use_infrastructure_delivery_safeguards", "housing_tenure_provider_models", "household_housing_affordability_dimensions", "public_social_community_housing_safeguards", "homelessness_shelter_supportive_housing_pathways", "housing_stability_displacement_protection_dimensions", "supportive_housing_service_dignity_safeguards", "retrofit_repair_decarbonization_capabilities", "climate_disaster_housing_safeguards", "relocation_reconstruction_right_to_return_safeguards", "long_horizon_place_stability_tests"]);
for (const [key, value] of Object.entries(registry.metrics)) if (!countKeys.has(key)) check(value === 0, `Phase 85 metric ${key} must remain zero.`);

const guideIds = ["briefing-housing-place-stability-doctrine-001", "briefing-housing-need-supply-delivery-001", "briefing-land-use-infrastructure-housing-delivery-001", "briefing-housing-habitability-accessibility-quality-001", "briefing-tenure-renter-homeowner-security-001", "briefing-public-social-cooperative-community-housing-001", "briefing-housing-affordability-cost-burden-001", "briefing-homelessness-shelter-supportive-housing-001", "briefing-indigenous-land-housing-rights-001", "briefing-retrofit-repair-decarbonization-001", "briefing-climate-disaster-housing-relocation-001", "briefing-reconstruction-right-to-return-place-stability-001"];
const mapIds = ["dependency-map-approved-units-are-not-delivered-homes", "dependency-map-shelter-bed-is-not-stable-housing", "dependency-map-affordability-label-is-not-household-affordability", "dependency-map-retrofit-spending-is-not-safe-habitable-housing", "dependency-map-temporary-relocation-is-not-right-to-return", "dependency-map-reconstruction-is-not-community-recovery"];
for (const id of guideIds) check(await exists(appRoot, "src", "content", "briefings", id + ".mdx"), `${id} is missing.`);
for (const id of mapIds) check(await exists(appRoot, "src", "content", "dependency-maps", id.replace("dependency-map-", "") + ".json"), `${id} is missing.`);
for (const pathwayId of new Set(delivery.flatMap((record) => record.reader_pathway_ids))) { const pathway = await readJson(appRoot, "src", "content", "reader-pathways", pathwayId.replace("reader-pathway-", "") + ".json"); check(guideIds.every((id) => pathway.briefing_ids.includes(id)) && mapIds.every((id) => pathway.dependency_map_ids.includes(id)), `${pathwayId} omits Phase 85 guides or maps.`); }
for (const record of delivery) check((await readText(appRoot, "src", "content", "briefings", record.canonical_briefing_id + ".mdx")).includes("## Phase 85 housing and place-stability boundary"), `${record.canonical_briefing_id} omits Phase 85.`);
for (const file of ["local-us-southwest-chip-corridor.mdx", "local-ontario-real-estate.mdx", "local-northern-virginia-data-center-corridor.mdx", "local-florida-space-coast-launch-corridor.mdx", "local-nevada-lithium-processing-corridor.mdx"]) check((await readText(appRoot, "src", "content", "local-systems", file)).includes("## Phase 85 housing, shelter, land use, and place-stability boundary"), `${file} omits Phase 85.`);
for (const file of ["briefing-outcomes-watch-001-what-actually-changed.mdx", "briefing-decision-accountability-desk-001.mdx", "briefing-universal-service-doctrine-001.mdx", "briefing-household-capability-doctrine-001.mdx", "briefing-community-institutions-doctrine-001.mdx", "briefing-essential-service-bundles-households-001.mdx", "briefing-disability-universal-design-home-community-001.mdx", "briefing-displacement-household-mobility-001.mdx", "briefing-crisis-stabilization-recovery-001.mdx", "briefing-emergency-rationing-restoration-long-horizon-accountability-001.mdx"]) check((await readText(appRoot, "src", "content", "briefings", file)).includes("## Phase 85 housing and place-stability control"), `${file} omits the Phase 85 operating control.`);

check(await exists(appRoot, "src", "pages", "evidence", "housing-place-stability", "index.astro") && await exists(appRoot, "src", "pages", "evidence", "housing-place-stability", "[id].astro") && await exists(appRoot, "src", "pages", "data", "housing-shelter-land-use-place-stability.json.ts"), "Phase 85 routes or export are missing.");
const dataIndex = await readText(appRoot, "src", "pages", "data", "index.astro"); check(dataIndex.includes("Housing, Shelter, Land Use And Place Stability") && dataIndex.includes("bounded public contracts"), "The data index omits Phase 85.");
const sitemap = await readText(appRoot, "src", "pages", "sitemap.xml.ts"); check(sitemap.includes("housingPlaceRegistry") && sitemap.includes("/evidence/housing-place-stability/"), "The sitemap omits Phase 85.");
const phase84Detail = await readText(appRoot, "src", "pages", "evidence", "food-systems", "[id].astro"); check(phase84Detail.includes("Phase 85 Destination") && phase84Detail.includes("/evidence/housing-place-stability/"), "Phase 84 detail routes omit the Phase 85 handoff.");
check(manifest.expected_build.static_pages >= 4897 && manifest.expected_build.public_json_exports >= 32 && manifest.expected_build.phase_85_housing_need_supply_delivery_habitability_dossiers === 8 && manifest.expected_build.phase_85_tenure_affordability_public_social_community_housing_ledgers === 8 && manifest.expected_build.phase_85_homelessness_shelter_supportive_housing_displacement_registers === 8 && manifest.expected_build.phase_85_retrofit_climate_disaster_reconstruction_place_stability_ledgers === 8 && manifest.expected_build.phase_85_synthetic_cases === 2560, "The release manifest omits Phase 85 counts.");
check(manifest.housing_need_supply_delivery_habitability_routes?.length === 8 && manifest.tenure_affordability_public_social_community_housing_routes?.length === 8 && manifest.homelessness_shelter_supportive_housing_displacement_routes?.length === 8 && manifest.retrofit_climate_disaster_reconstruction_place_stability_routes?.length === 8, "The release manifest omits Phase 85 routes.");

if (failures.length) { console.error(`Phase 85 assertions failed with ${failures.length} issue(s):`); failures.forEach((failure) => console.error(`- ${failure}`)); process.exit(1); }
console.log("Phase 85 assertions passed: 8 inactive delivery dossiers, 8 inactive tenure ledgers, 8 inactive stability registers, 8 inactive place ledgers, 84 gates per chain, exact taxonomies, 10 pathways, and 0 approvals, allocations, placements, findings, relocations, returns, remedies, receipts, scores, rankings, or stage changes.");
